### ISSUE TITLE
[ServerException] - 3D Secure - Android

### ISSUE THREAD

**Issue by hoordev** [braintree/braintree_android#326] opened 2021-01-11 12:58 UTC
### General information

* SDK/Library version: 3.15.0
* Environment: Production
* Android Version and Device: Samsung Galaxy S9 Plus with Android 10

Braintree dependencies:

-  com.braintreepayments.api:braintree:3.15.0
-  com.braintreepayments.api:three-d-secure:3.15.0
-  com.braintreepayments:card-form:5.0.0

### Issue description

My application uses Braintree payments with custom ui. When I would implement the 3D Secure method, I got error from Briantree sdk. The own system contains backend, that allocate token for mobiles. The ios version of development are working on production environment (or sandbox), just android not. The sdk description are easy and clean: Put sdk to gradle, Initialize Braintree fragment with received authorization, Create/Get CardNonce and Perform Three Secure verification with lookup listener, and so on. Everything ok. After I would pay on own PaymentFragment I got the following error from Braintree sdk.

The masked url when I receive error: 
https://api.braintreegateway.com:443/merchants/AABBCC/client_api/v1/payment_methods/AABBCC/three_d_secure/lookup
Response code: 500

The next flow is where the code no longer reaches:

`ThreeDSecure.continuePerformVerification(braintreeFragment, request, lookup)`

### Crash log

`PaymentFragment: Braintree error
    com.braintreepayments.api.exceptions.ServerException: {}
        at com.braintreepayments.api.internal.HttpClient.parseResponse(HttpClient.java:272)
        at com.braintreepayments.api.internal.BraintreeHttpClient.parseResponse(BraintreeHttpClient.java:138)
        at com.braintreepayments.api.internal.HttpClient.post(HttpClient.java:219)
        at com.braintreepayments.api.internal.BraintreeHttpClient.post(BraintreeHttpClient.java:121)
        at com.braintreepayments.api.internal.HttpClient$2.run(HttpClient.java:186)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)`

Any suggestion?
This problem reproducible on any device with any android os version.

**Comment by sshropshire** [comment] 2021-01-11 14:59
Hello @hoordev thanks for using the Braintree SDK for Android. Does your integration differ in any way from the [docs](https://developers.braintreepayments.com/guides/3d-secure/client-side/android/v3)? Also, does the `ServerException` instance's `getMessage()` method return any useful information?

**Comment by hoordev** [comment] 2021-01-11 15:11
No, no customization at implementation.
Exception details

![image](https://user-images.githubusercontent.com/4958355/104198743-df7e0300-5426-11eb-89e6-edfe943d07ff.png)

**Comment by sshropshire** [comment] 2021-01-11 19:52
@hoordev thanks. Can you provide a snippet of how you're constructing the actual `ThreeDSecureRequest` ?

**Comment by hoordev** [comment] 2021-01-11 20:01
![image](https://user-images.githubusercontent.com/4958355/104231867-d7868900-544f-11eb-87a7-d64a6b1021c0.png)
![image](https://user-images.githubusercontent.com/4958355/104231906-e3724b00-544f-11eb-92c5-3dbc007e3a40.png)
![image](https://user-images.githubusercontent.com/4958355/104231699-a0b07300-544f-11eb-8146-554f0949e022.png)
![image](https://user-images.githubusercontent.com/4958355/104231619-84acd180-544f-11eb-81bc-080a67631222.png)

**Comment by sshropshire** [comment] 2021-01-11 21:16
@hoordev nothing jumps out as being different from our demo application so far. Does this work in the emulator currently?

The only thing worth double-checking is that the request doesn't contain any `null` values e.g. amount, some field in the shipping address.

**Comment by sshropshire** [comment] 2021-01-11 22:00
@hoordev I noticed the amount field has a space in it. Maybe that can cause an issue on lookup? A `.` or `,` may be needed to differentiate dollars / cents.

**Comment by crookedneighbor** [comment] 2021-01-11 22:15
^ I've confirmed that sending the amount as `100 00` causes a 500 response in our API. I'm going to let our 3D Secure team know about it.

**Comment by hoordev** [comment] 2021-01-11 22:29
Oh, thanks. I tested without spaces and now working, but I not created 100% test. The built in Chrome Tabs mode are opened and loaded Revolut 3D Secure page. I will continue tomorrow.

I suggest update sdk docs with exact request description.

**Comment by sshropshire** [comment] 2021-01-12 15:49
Awesome @hoordev thanks for your feedback. I'm going to close this issue for now since you're now able to successfully perform a 3DS lookup.

**Closed by sshropshire** 2021-01-12 15:49 UTC
