### ISSUE TITLE
OnNewIntent not being called after close the webview

### ISSUE THREAD

**Issue by fernandohbrasilpoq** [braintree/braintree_android#479] opened 2021-11-22 14:53 UTC
### General information

* SDK/Library version: 4.8.0
* Environment: Production
* Android Version and Device: Xiaomi A3 - Android 11
* Braintree dependencies: `com.braintreepayments.api:paypal:4.8.0`

### Issue description

After I open the Paypal WebView (tokenizePayPalAccount) and close on the "X" or press back on the device the overridden `OnNewIntent` on the activity is NOT being called, so I am not able to take any action.

**Comment by fernandohbrasilpoq** [comment] 2022-01-14 09:24
can someone check this, please?

**Comment by sarahkoop** [comment] 2022-01-14 14:53
Hi @fernandohbrasilpoq - Apologies for the delayed response. We are aware that there seems to be some inconsistency in the `onNewIntent` behavior in certain Android API versions and devices. We are currently investigating this issue and will post an update here when we have more information.

**Comment by sarahkoop** [comment] 2022-01-20 20:44
Hi @fernandohbrasilpoq - After further investigation, it does not seem like this is an issue with `onNewIntent`. The expected behavior for cancelling out of the PayPal window (Chrome Custom Tab) by clicking the “X”, is to return to the same `Activity` where it was launched. In this case, `onResume` will be called, and if you are handling the browser switch result in `onResume` based on the integration guide, you should receive the cancellation result there.

The exception to this is if the launching Activity is destroyed after launching the browser, then a new Activity will be re-created, in which case `onNewIntent` will also not be called, but `onResume` should be, and the result can also be handled there.

I'm going to close this issue out, but please feel free to re-open if you are experiencing an issue other than the expected behavior.

**Closed by sarahkoop** 2022-01-20 20:44 UTC
