### ISSUE TITLE
Native check out call back not triggering after logged in.

### ISSUE THREAD

**Issue by najeer57** [braintree/braintree_android#884] opened 2024-01-11 08:09 UTC
### Braintree SDK Version

4.40.1

### Environment

Sandbox

### Android Version & Device

Samsung s20

### Braintree dependencies

Implementation 'com.braintreepayments.api.paypal-native-checkout:4.40.1'

### Describe the bug

I am using native checkout through sandbox account. I can able to logged in through app using external browser but after logged in callback not triggering to our app. Its keep on loading in external browser itself. I have also faced the same issue with this normal checkout dependencies "com.braintreepayments.api:paypal:4.40.1". But after added the browserSwitchResult in OnResume the callback getting fine to our app as mentioned below code.
 protected void onResume() { 
super.onResume(); BrowserSwitchResult browserSwitchResult = payPalClient.parseBrowserSwitchResult(this, getIntent()); 
if (browserSwitchResult != null) { handleBrowserSwitchResult(browserSwitchResult); 
}
 } 

But we can't use this parseBrowserSwitchResult to "payPalNativeCheckoutClient" as it throws error.

 Below is my manifest file: 
<activity android:name=".activity.PaypalNativeCheckout" android:exported="true" android:launchMode="singleTask" android:screenOrientation="portrait"> 
<intent-filter>
 <data android:scheme="${applicationId}.braintree" /> <action android:name="android.intent.action.VIEW" /> <category android:name="android.intent.category.DEFAULT" /> <category android:name="android.intent.category.BROWSABLE" /> 
</intent-filter>
 </activity>

 I am passing the return url as with my application package id end with ://paypalpay (com.campanyname.paypaldemo://paypal) as I registered this to sandbox account also. 
I have initialised paypal client in our PaypalNativeCheckout activity:

 public class PaypalNativeCheckout extends AppCompatActivity implements PayPalNativeCheckoutListener {
 // Initialisation comes here. 
private void initialisePaypalClient() { braintreeClient = new BraintreeClient(this, "paypalClientToken_value"); payPalNativeCheckoutClient = new PayPalNativeCheckoutClient(braintreeClient); payPalNativeCheckoutClient.setListener(this); 
} 
private void launchPayPalNativeCheckout(boolean isBilling) {
 PayPalNativeCheckoutRequest request = new PayPalNativeCheckoutRequest("1"); request.setCurrencyCode("GBP"); request.setReturnUrl("com.companyname.nativecheckout://paypalpay"); payPalNativeCheckoutClient.launchNativeCheckout(this, request);
 } 
} 
Please assist me to resolve this issue.

### To reproduce

Open app - click PayPal pay - app navigates to external browser - log in with sandbox account - then keeps on loading in browser after logged in

### Expected behavior

App should navigate to app after logged in external browser and showing the user wallet

**Comment by sarahkoop** [comment] 2024-01-11 15:10
Hi @najeer57 - Thanks for using the Braintree Android SDK! The PayPalNativeCheckout flow works differently from the PayPal web-based flow, so the browser switch result parsing code you included is required for the PayPal module, but not the PayPalNativeCheckout module.

The code snippet of your manifest didn't come through, so I can't say for certain if there is an issue there, but otherwise the code snippets provided look to be set up correctly. If the manifest is also configured correctly, it sounds like the issue is likely with the setup of the return URL linked to your account. If you've already followed all of the [steps outlined in the docs](https://developer.paypal.com/braintree/docs/guides/paypal/mobile-checkout/android/v4#register-the-apps-returnurl) to register your return URL, I would recommend [reaching out to our technical support team](https://developer.paypal.com/braintree/help/) who can help confirm that the account is set up correctly.

**Comment by najeer57** [comment] 2024-01-18 10:25
Issue is with return url, fixed now

**Comment by sarahkoop** [comment] 2024-01-18 14:40
Great - glad it was resolved! Closing this issue now 👍

**Closed by sarahkoop** 2024-01-18 14:40 UTC
