### ISSUE TITLE
Migration paypal v5: PayPalPaymentAuthResult - NoResult 

### ISSUE THREAD

**Issue by javier-28** [braintree/braintree_android#1184] opened 2024-10-09 15:26 UTC
### Braintree SDK Version

5.0

### Environment

Sandbox

### Android Version & Device

Pixel 4 XL API 34

### Braintree dependencies

com.braintreepayments.api:paypal

### Describe the bug

I am in the process of updating the PayPal library to version 5.0. I am founding the following issue:

The WebView is displayed, and we can authenticate on the PayPal platform. You can select the payment method and press continue. 
The deeplink opens, and it redirects back to the app, but the success case is not reached. The result of the method is `PayPalPaymentAuthResult.NoResult`.

I don't understand why it's always reaching this scenario.

I would like to know at least what situations cause the result of the` payPalLauncher.handleReturnToApp()` function to be `PayPalPaymentAuthResult.NoResult` 
so I can follow that thread and review the implementation.

The project is a React native application with a Native module for braintree payments 

### To reproduce

I have been able to reproduce it in two different ways.

The first one by launching a new activity from the native RN module, and the second by implementing the PayPal flow within an RN module.

The fact that I can reproduce the issue from two different scenarios makes me think that the problem might be caused by some external factor that I am not seeing. 
I can provide the full code for both scenarios if you think it’s necessary.

            payPalClient.createPaymentAuthRequest(reCurrentActivity!!, request) { paymentAuthRequest ->
                when (paymentAuthRequest) {
                    is PayPalPaymentAuthRequest.ReadyToLaunch -> {
                        val pendingRequest = payPalLauncher.launch(reCurrentActivity!!, paymentAuthRequest)
                        when (pendingRequest) {
                            is PayPalPendingRequest.Started -> {
                                pendingString = pendingRequest.pendingRequestString
                            }

                            is PayPalPendingRequest.Failure -> {
                                mPromise.reject("BraintreeSDK Error", pendingRequest.error.message)
                            }
                        }
                    }

                    is PayPalPaymentAuthRequest.Failure -> {
                        mPromise.reject("BraintreeSDK Error",paymentAuthRequest.error.message)

                    }
                }
            }

        private fun handleReturnToApp(intent: Intent) {
            // fetch stored PayPalPendingRequest.Success
            if(this::pendingString.isInitialized){
                when (val paymentAuthResult = payPalLauncher.handleReturnToApp(PayPalPendingRequest.Started(pendingString), intent)) {
                    is PayPalPaymentAuthResult.Success -> {
                        completePayPalFlow(paymentAuthResult)
                        // clear stored PayPalPendingRequest.Success
                    }
                    is PayPalPaymentAuthResult.NoResult -> {
                        // user returned to app without completing PayPal flow, handle accordingly
                        mPromise.reject("BraintreeSDK Error","NO RESULT")

                    }
                    is PayPalPaymentAuthResult.Failure ->  {

                        mPromise.reject("BraintreeSDK Error", paymentAuthResult.error.message)
                        // handle error case
                    }
                }
            }
        }

### Expected behavior

Enter the Success case of PayPalPaymentAuthResult.

### Screenshots

https://github.com/user-attachments/assets/4dcce35b-108b-44b1-b827-dde42ea52da7

**Comment by javier-28** [comment] 2024-10-21 05:51
hi, any news?

**Comment by saperi22** [comment] 2024-10-25 16:19
@javier-28 unfortunately, we do not test for or support react native integrations.
That being said, please let us know if this integration fails for native modules too.

**Comment by javier-28** [comment] 2024-10-29 09:48
Hi @saperi22,

Thank you for your response. We understand that you don’t provide support specifically for React Native implementations; I mentioned it earlier only to clarify the overall context. However, as explained in the initial ticket, the integration we’re using here is native, implemented in Kotlin.

The specific issue arises when calling the function `payPalLauncher.handleReturnToApp(PayPalPendingRequest.Started(pendingString), intent).` Each time, the result we receive is `PayPalPaymentAuthResult.NoResult.`

As you can see in the attached video, there are no authorization issues when selecting the payment method.

We would greatly appreciate it if you could told us any factors or dependencies that might lead to consistently obtaining a `PayPalPaymentAuthResult.NoResult.`

**Comment by saperi22** [comment] 2024-10-31 21:14
@javier-28 can you please confirm if you've followed the steps mentioned in the [v5_MIGRATION_GUIDE](https://github.com/braintree/braintree_android/blob/main/v5_MIGRATION_GUIDE.md#paypal), specifically the [App link setup](https://github.com/braintree/braintree_android/blob/main/APP_LINK_SETUP.md)?

**Comment by javier-28** [comment] 2024-11-05 16:03
@saperi22 Yes, we have followed Yes, the steps in the guide.

**Comment by saperi22** [comment] 2024-11-05 19:32
@javier-28 would you be able to provide a minimally reproducible sample for this issue?
Please do not include any sensitive information.

**Comment by Pavel87** [comment] 2024-11-14 06:21
Hi @saperi22,
We are just updating to 5.2 and having same issue where result goes to `NoResult`. After login inside PayPal the app switch correctly back and intent received seems to have a valid data but still the result of `payPalLauncher.handleReturnToApp` is always `NoResult`

**intent data:** `some.app.with.braintree://onetouch/v1/success?token=EC-8MX176168Y683725R&ba_token=BA-28N28838CH4927537`

- SDK version 5.2
- We have native kotlin app

**Comment by DukeNuker** [comment] 2024-11-20 13:41
I also have the same problem. It returns NoResult instead of Success, although in the browser it looks like it was successful.

SDK 5.2.0 and native kotlin app

**Comment by saperi22** [comment] 2024-11-20 23:45
> Hi @saperi22, We are just updating to 5.2 and having same issue where result goes to `NoResult`. After login inside PayPal the app switch correctly back and intent received seems to have a valid data but still the result of `payPalLauncher.handleReturnToApp` is always `NoResult`
> 
> **intent data:** `some.app.with.braintree://onetouch/v1/success?token=EC-8MX176168Y683725R&ba_token=BA-28N28838CH4927537`
> 
> * SDK version 5.2
> * We have native kotlin app

Can you confirm if that was in sandbox or production?

**Comment by saperi22** [comment] 2024-11-21 18:59
@javier-28 @Pavel87 @DukeNuker Can you all confirm one thing for me.
Is 'Open supported links' set to 'Allow app to open supported links' in your app settings? [Long click on the app icon -> App Info &#9432; -> Advanced -> Open by default -> Open supported links]

**Comment by DukeNuker** [comment] 2024-11-22 07:07
@saperi22  Yes this is allowed. I think I've found the problem. I didn't set the App Link Support in the PayPal Control Panel (https://github.com/braintree/braintree_android/blob/main/APP_LINK_SETUP.md). I can't set it now and test it, because my customer needs to do that (I don't have the rights yet). Could this be the reason? If so, then the "NoResult" error does not indicate that.

**Comment by saperi22** [comment] 2024-12-04 20:22
@DukeNuker yes, we expect you to set the return url in the domain names section of the control panel.
We'll take your feedback into consideration on surfacing better messaging for when control panel is not setup properly.

**Comment by saperi22** [comment] 2024-12-04 20:33
I'm going to close this as there hasn't been any activity from the OP on their issue. There's not enough actionable information for us to go off of.

Here are a few scenarios in which `NoResult` is to be expected.

- App link setup isn’t done properly -- please follow steps in [App link setup](https://github.com/braintree/braintree_android/blob/main/APP_LINK_SETUP.md) to properly setup app links.

- "Open supported links" is not checked -- this is an end user setting. We are actively working on enabling falling back to deep links if the end user has chosen not to allow app links. See https://github.com/braintree/braintree_android/pull/1223. We'll publish instructions once we are ready to release.

- CCT going into Picture-in-picture mode -- See: https://github.com/braintree/braintree_android/blob/main/v5_MIGRATION_GUIDE.md#chrome-custom-tab-picture-in-picture

**Closed by saperi22** 2024-12-04 20:33 UTC

**Comment by rsousabluebeck** [comment] 2025-06-16 11:46
For anyone who might struggle finding an answer to this, what resolved the issue for me was to capture the intent in the activity with the override of `onNewIntent` instead of `onResume` as the documentation suggests we do for all `launchMode` other than `singleTop`. I had mine set to `singleTask` and was constantly getting `data` as null from `getIntent()` on the `onResume` method.

<img width="500" alt="Image" src="https://github.com/user-attachments/assets/ec93bdc7-fcce-4e05-b03d-5ef569f675ef" />
