### ISSUE TITLE
404 not found when trying to create a transaction

### ISSUE THREAD

**Issue by copypasteearth** [braintree/braintree_android#247] opened 2019-03-11 22:02 UTC
hello all im using the rails server on Heroku and im trying to test an android app that im working on and I keep getting a 404 error when I try to create a transaction. I can get the client token but im getting 404 not found when making a transaction. I just cloned this repo and im running the demo app.

if you need any more info let me know what to post and thank you for your time

**Comment by crookedneighbor** [comment] 2019-03-12 01:40
Closing as a duplicate of https://github.com/braintree/braintree_rails_example/issues/45

**Closed by crookedneighbor** 2019-03-12 01:40 UTC
