### ISSUE TITLE
Android P Attribute not found

### ISSUE THREAD

**Issue by hokifydavid** [braintree/braintree_android#216] opened 2018-07-04 09:27 UTC
### General information

* SDK/Library version: 
* Environment: 
* Android Version and Device: 
* Braintree dependencies: 
implementation('com.braintreepayments.api:braintree:2.14.0')
implementation('com.braintreepayments.api:drop-in:3.3.0')
implementation 'com.braintreepayments.api:data-collector:2.13.0'

--> no it's not a drop in issue

### Issue description

If updating the Android support libraries (com.android.support:*) there's an error while compiling

error: style attribute 'attr/textColorError (aka com.yfabrik.hocknfinder:attr/textColorError)' not found.
Message{kind=ERROR, text=error: style attribute 'attr/textColorError (aka com.yfabrik.hocknfinder:attr/textColorError)' not found., sources=[C:\Users\david\.gradle\caches\transforms-1\files-1.1\card-form-3.3.0.aar\dcd6443e429152b5528b5b6fdfc5b097\res\values\values.xml:55:5-57:13], original message=, tool name=Optional.of(AAPT)}

I suppose there is a wrong resource reference in your library called with @attr/textColorError instead of attr/textColorError. *** mind the @ ***

Workaround: Overwrite the attr/textColorError globally

greetings from Vienna

**Comment by quinnjn** [comment] 2018-07-05 23:20
This looks like it is coming from a library inside Drop-in, [braintree/android-card-form](https://github.com/braintree/android-card-form).

We have an existing issue open in braintree/braintree-android-drop-in#77 around `textColorError`.

We are in the process of [upgrading our libraries for Android P](https://github.com/braintree/braintree_android/issues/210), and this is a fix we're working as part of that.

Closing as a duplicate of braintree/braintree-android-drop-in#77

**Closed by quinnjn** 2018-07-05 23:20 UTC
