### ISSUE TITLE
Fatal Exception: java.lang.IllegalStateException in GooglePayLifecycleObserver.java

### ISSUE THREAD

**Issue by SirLordPouya** [braintree/braintree_android#597] opened 2022-09-28 14:19 UTC
### General information

* SDK/Library version: 4.12.0
* Environment: Production
* Android Version and Device: One Plus Nord with Android 11, One Plus 8 Pro with Android 12, Galaxy s21 Ultra 5G with Android 12, Galaxy Note 10 with Android 12
* Braintree dependencies:
```
com.braintreepayments.api.braintree-core
com.braintreepayments.api.data-collector
com.braintreepayments.api.google-pay
com.braintreepayments.api.three-d-secure

```
### Issue description

We are facing this crash on some of our devices in production with the following exception:

```
Fatal Exception: java.lang.IllegalStateException
Attempting to launch an unregistered ActivityResultLauncher with contract com.braintreepayments.api.n0@7d2cc6d and input com.braintreepayments.api.t0@85870a2. You must ensure the ActivityResultLauncher is registered before calling launch().
androidx.activity.result.ActivityResultRegistry$2.launch (ActivityResultRegistry.java:167)
androidx.activity.result.ActivityResultLauncher.launch (ActivityResultLauncher.java:47)
arrow_right
com.braintreepayments.api.GooglePayLifecycleObserver.launch (GooglePayLifecycleObserver.java:44)
com.braintreepayments.api.GooglePayClient$4$1.onResult (GooglePayClient.java:296)
com.braintreepayments.api.ConfigurationLoader$1.onResult (ConfigurationLoader.java:52)
com.braintreepayments.api.HttpClient$2.run (HttpClient.java:123)
android.os.Handler.handleCallback (Handler.java:938)
android.os.Handler.dispatchMessage (Handler.java:99)
android.os.Looper.loop (Looper.java:245)
android.app.ActivityThread.main (ActivityThread.java:8024)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:631)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:978)
```

**Comment by sshropshire** [comment] 2022-09-28 14:41
Hi @SirLordPouya thanks for using the Braintree SDK for Android. This is a duplicate of #543. Please see [the proposed workaround](https://github.com/braintree/braintree_android/issues/543#issuecomment-1198332647) in the meantime while we prioritize a long term fix.

Closing this for now.

**Closed by sshropshire** 2022-09-28 14:41 UTC
