### ISSUE TITLE
Error message for: AndroidManifest.xml is incorrectly configured or another app...

### ISSUE THREAD

**Issue by Pingapplepie** [braintree/braintree_android#630] opened 2022-12-07 07:27 UTC
**Integration Details (please complete the following information):**

* SDK/Library version: 4.12.0
* Environment: Production
* Android Version and Device: Android 8.0+
* Braintree dependencies:
implementation com.braintreepayments.api:card:4.12.0
implementation com.braintreepayments.api:paypal:4.12.0
implementation com.braintreepayments.api:data-collector:4.12.0
implementation com.braintreepayments.api:three-d-secure:4.12.0

**Describe the bug**
There is an error message reported on some rare cases from users who installed our android apps,  which says:
```
"AndroidManifest.xml is incorrectly configured or another app defines the same browser switch url as this app. 
See https://developers.braintreepayments.com/guides/client-sdk/android/#browser-switch for the correct configuration". 
```
I checked the source code of braintree SDK, and it seems there are just two cases that will report this error, one is there is no valid Activity declared in the manifest to handle the deep link of Braintree and the other is there is no valid web browser to handle HTTPS scheme. Since our app works for million users and our QA has verified all workflow, it shouldn't be the manifest issue, otherwise, this will happen for all users. So I guess this is caused by web browser, then I have asked all our users to install Chrome as the default web browser, but some of them still say it doesn't work.
Do you have any suggestions on this issue? Could you please send the real error message to apps, instead of the general message? 

![image](https://user-images.githubusercontent.com/42831065/206114699-43197801-1446-441b-9049-61e2979f9abe.png)

**Comment by sshropshire** [comment] 2022-12-07 15:34
Hi @Pingapplepie thanks for using the Braintree SDK for Android. Do you specify a `customUrlScheme` when instantiating a `BraintreeClient`?

This does sound odd. Do you have more information about the specific users experiencing this issue i.e. do their devices, OS versions have similarities?

**Comment by bm185178** [comment] 2022-12-08 15:22
We are having same issue

AndroidManifest.xml is incorrectly configured or another app defines the same browser switch url as this app. See https://developers.braintreepayments.com/guides/client-sdk/android/#browser-switch for the correct configuration

```
    api 'com.braintreepayments.api:drop-in:6.5.0'
    implementation 'com.braintreepayments.api:data-collector:4.20.0'
```

Tried 
https://developer.paypal.com/braintree/docs/guides/client-sdk/setup
```
<activity android:name="com.company.MyActivity"
    android:exported="true">
    <intent-filter>
        <action android:name="android.intent.action.VIEW" ></action>
        <category android:name="android.intent.category.DEFAULT" ></category>
        <category android:name="android.intent.category.BROWSABLE" ></category>
        <data android:scheme="${applicationId}.braintree" ></data>
    </intent-filter>
</activity>

**Comment by sshropshire** [comment] 2022-12-08 19:11
@Pingapplepie thank you. That looks standard. Can you update to the latest [4.20.0](https://github.com/braintree/braintree_android/issues/630) version?

Also, would you mind step through debugging down into the `browserSwitchInspector` implementation to find out exactly why the exception occurs on your device?

**Comment by Pingapplepie** [comment] 2022-12-09 03:29
@sshropshire this does not happen on my device, so I cannot debug into it. And we will upgrade to 4.20.0 recently. I just wonder whether you can post the exact error message by the error callback, then we can learn more on this case.

**Comment by bm185178** [comment] 2022-12-09 20:52
Had same issue. Make sure use lower cased applicationId on your payment activity. This resolved it for me with 4.20.0

**Comment by sshropshire** [comment] 2022-12-12 17:51
Hi @Pingapplepie does @bm185178 's [suggestion](https://github.com/braintree/braintree_android/issues/630#issuecomment-1344770020) work for your app?

**Comment by Pingapplepie** [comment] 2023-01-04 06:43
@sshropshire @bm185178 's feedback doesn't work for me. I checked our application id are all lowercase letters.

**Comment by sshropshire** [comment] 2023-01-30 20:45
@Pingapplepie @kostiantyn-solianyk does your app package name contain underscores?

**Comment by Pingapplepie** [comment] 2023-02-01 07:40
@sshropshire , our package name doesn't contain any underscores, just like com.companyname.app

**Comment by Tobbb** [comment] 2023-02-01 14:55
Just got the same issue reported but works for me, first time I saw it

could it be related to device?

braintreeSDKVersion = "4.20.0"
OnePlus GM1903
OS Level 30

`"error":{"nativeStackAndroid":[],"userInfo":null,"message":"AndroidManifest.xml is incorrectly configured or another app defines the same browser switch url as this app. See https://developers.braintreepayments.com/guides/client-sdk/android/#browser-switch for the correct configuration`

**Comment by sshropshire** [comment] 2023-02-01 20:48
@Tobbb has your integration been successful?

@Pingapplepie @kostiantyn-solianyk Could you set a breakpoint here in [BraintreeClient.java](https://github.com/braintree/braintree_android/blob/b0d780f3aaf443727dbe073ddfabffb94a871789/BraintreeCore/src/main/java/com/braintreepayments/api/BraintreeClient.java#L307) and step through debug to help identify the root cause of the issue on your device?

**Comment by Pingapplepie** [comment] 2023-02-07 07:15
@sshropshire sorry, I cannot reproduce this issue from my side. Just some of our users reported this issue, I am also not quite sure why this will happen.

**Comment by Tobbb** [comment] 2023-02-08 12:39
> @Tobbb has your integration been successful?
> 
> @Pingapplepie @kostiantyn-solianyk Could you set a breakpoint here in [BraintreeClient.java](https://github.com/braintree/braintree_android/blob/b0d780f3aaf443727dbe073ddfabffb94a871789/BraintreeCore/src/main/java/com/braintreepayments/api/BraintreeClient.java#L307) and step through debug to help identify the root cause of the issue on your device?

i assume yes since there have only been one instance of this issue. I can not reproduce it  and a lot of payments work

**Comment by sshropshire** [comment] 2023-02-08 15:28
@Pingapplepie @kostiantyn-solianyk @Tobbb I have a PR open to append the original browser switch error message into the error output. Hopefully this will give us more information and lead us toward a fix 🤞.

**Comment by sshropshire** [comment] 2023-03-01 17:22
@Pingapplepie @kostiantyn-solianyk @Tobbb checking in. Is there any new information available from the crash logs that could help us identify the issue?

**Comment by Pingapplepie** [comment] 2023-03-09 00:11
@sshropshire provided crash track logs as below:
com.braintreepayments.api.BraintreeException: AndroidManifest.xml is incorrectly configured or another app defines the same browser switch url as this app. See https://developers.braintreepayments.com/guides/client-sdk/android/#browser-switch for the correct configuration
	at com.braintreepayments.api.ThreeDSecureClient$1.onResult(ThreeDSecureClient.java:62)
	at com.braintreepayments.api.BraintreeClient$1$1.onResult(BraintreeClient.java:12)
	at com.braintreepayments.api.ConfigurationLoader$1.onResult(ConfigurationLoader.java:29)
	at com.braintreepayments.api.HttpClient$2.run(HttpClient.java:6)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:236)
	at android.app.ActivityThread.main(ActivityThread.java:7889)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:600)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)

**Comment by sshropshire** [comment] 2023-04-06 14:36
Hey @Pingapplepie any update on this?

**Comment by ajeihala** [comment] 2023-04-17 10:49
We were having the same issue with 3ds2 flow
```
com.braintreepayments.api.BraintreeException: AndroidManifest.xml is incorrectly configured or another app defines the same browser switch url as this app. See https://developer.paypal.com/braintree/docs/guides/client-sdk/setup/android/v4#browser-switch-setup for the correct configuration: No installed activities can open this URL: https://braintreepayments.com/
```

By some reason Braintree SDK `deviceHasBrowser()` method inside `BrowserSwitchClient.assertCanPerformBrowserSwitch()` tells there's no browsers in the system. It doesn't seem to matter which url is in the `AndroidManifest` because it just checks if anything resolved to view url `"https://"`.

This issue was the top 3ds2 error but after updating to SDK version 4.27.0 this error seems to fade out, we don't see it any more in our monitoring. We'll continue checking the errors in future to ensure the issue is completely gone.

It may be related to the 3ds1 fallback deprecation and [this commit](https://github.com/braintree/braintree_android/commit/22d5fffe481469f85a14266a694ff19d9fea4755) that ensures browser check only for 3ds1.

**Comment by sshropshire** [comment] 2023-04-17 14:18
Hi @ajeihala correct, we've phased out this error for 3DS. We realized a browser check for 3DS v2 is unnecessary, and since 3DS v1 is fully deprecated we were able to skip the browser check.

On the other hand, it is still possible for other payment flows that use chrome custom tabs to fail when no browser exists on the device.

**Comment by sshropshire** [comment] 2023-04-17 16:05
@ajeihala out of curiosity have you been able to reproduce this 100% of the time on your device / emulator with older versions? If so, could we get the device manufacturer, model, and Android OS version so we can try to reproduce the issue for other payment methods?

**Comment by sshropshire** [comment] 2023-04-17 18:58
@ajeihala is their any additional information in the crash logs about the environment that causes the error?

**Comment by ajeihala** [comment] 2023-04-17 19:59
It was not a crash but normal `BraintreeException` from 3ds2 flow, just a payment error. We didn't find anything specific to help with the issue investigation as devices seem to be random. And still, I have doubts that so many people who use apps and willing to pay online don't have a browser on their phone, which can handle a url. So something either in permissions or the method itself to detect a browser might be not reliable.

```
boolean deviceHasBrowser(Context context) {
    Intent browserSwitchIntent = new Intent(Intent.ACTION_VIEW, Uri.parse("https://"));
    return canResolveActivityForIntent(context, browserSwitchIntent);
}

private boolean canResolveActivityForIntent(Context context, Intent intent) {
    return !context.getPackageManager().queryIntentActivities(intent, 0).isEmpty();
}
```

Just a guess, did you try `queryIntentActivities()` with other flags, like `PackageManager.MATCH_DEFAULT_ONLY` or `MATCH_ALL`?

**Comment by sshropshire** [comment] 2023-04-27 18:31
Hi @ajeihala we haven't tried those flags, but after some discussion we're going to remove the browser assertion since it seems unnecessary. Here's the PR in our [browser-switch-android](https://github.com/braintree/browser-switch-android/pull/63) repo. Once it gets merged in we'll update the Core SDK to point to the new version and hopefully resolve this issue.

**Comment by sarahkoop** [comment] 2023-08-28 19:33
Hi all - we've released the above mentioned browser switch changes and they are available in version 4.36.0 and later of the SDK. Can anyone confirm if this issue is still existing or resolved?

**Comment by ajeihala** [comment] 2023-08-29 15:54
We are on the version 4.35.0 with no browser switch changes or modifications from our side and the error "AndroidManifest.xml is incorrectly configured ..." seems to be completely gone by now.

**Comment by sarahkoop** [comment] 2023-08-29 16:03
Great! Closing this issue out - but feel free to re-open if the issue persists.

**Closed by sarahkoop** 2023-08-29 16:03 UTC

**Comment by Jake-Jiang** [comment] 2024-11-05 08:40
issue still  persists
