### ISSUE TITLE
TransactionTooLargeException in com.braintreepayments.api.ThreeDSecureActivity

### ISSUE THREAD

**Issue by IgorButirsky** [braintree/braintree_android#642] opened 2022-12-28 12:35 UTC
**Integration Details (please complete the following information):**

* SDK/Library version: 4.18.0 (also tried 4.22.0)
* Environment: Production
* Android Version and Device: Pixel 7 Pro with Android 13, emulator of Pixel 3a with Android 12
* Braintree dependencies:
    - com.braintreepayments.api:card:4.18.0
    - com.braintreepayments.api:data-collector:4.18.0
    - com.braintreepayments.api:three-d-secure:4.18.0

**Describe the bug**
The app crashes during the 3D Secure payment with `TransactionTooLargeException`.

***Stacktrace:***
```
Transaction too large, intent: Intent { cmp=com.main.gopuff/com.braintreepayments.api.ThreeDSecureActivity (has extras) }, extras size: 683584, icicle size: 0
Second failure launching com.main.gopuff/com.braintreepayments.api.ThreeDSecureActivity, giving up
                                           android.os.TransactionTooLargeException: data parcel size 686688 bytes.   
    at android.os.BinderProxy.transactNative(Native Method)
    at android.os.BinderProxy.transact(BinderProxy.java:571)
    at android.app.IApplicationThread$Stub$Proxy.scheduleTransaction(IApplicationThread.java:2732)
    at android.app.servertransaction.ClientTransaction.schedule(ClientTransaction.java:136)
    at com.android.server.wm.ClientLifecycleManager.scheduleTransaction(ClientLifecycleManager.java:47)
    at com.android.server.wm.ActivityTaskSupervisor.realStartActivityLocked(ActivityTaskSupervisor.java:868)
    at com.android.server.wm.ActivityTaskSupervisor.startSpecificActivity(ActivityTaskSupervisor.java:986)
    at com.android.server.wm.Task.resumeTopActivityInnerLocked(Task.java:6561)
    at com.android.server.wm.Task.resumeTopActivityUncheckedLocked(Task.java:6132)
    at com.android.server.wm.Task.resumeTopActivityUncheckedLocked(Task.java:6177)
    at com.android.server.wm.RootWindowContainer.resumeFocusedTasksTopActivities(RootWindowContainer.java:2364)
    at com.android.server.wm.RootWindowContainer.resumeFocusedTasksTopActivities(RootWindowContainer.java:2311)
    at com.android.server.wm.RootWindowContainer.resumeFocusedTasksTopActivities(RootWindowContainer.java:2306)
    at com.android.server.wm.ActivityTaskManagerService$LocalService.handleAppDied(ActivityTaskManagerService.java:5760)
    at com.android.server.am.ActivityManagerService.handleAppDiedLocked(ActivityManagerService.java:3026)
    at com.android.server.am.ActivityManagerService.appDiedLocked(ActivityManagerService.java:3122)
    at com.android.server.am.ActivityManagerService$AppDeathRecipient.binderDied(ActivityManagerService.java:1437)
    at android.os.IBinder$DeathRecipient.binderDied(IBinder.java:314)
    at android.os.BinderProxy.sendDeathNotice(BinderProxy.java:685)

```

***Stacktrace at the moment of starting ThreeDSecureActivity:***

```
    at com.braintreepayments.api.ThreeDSecureLifecycleObserver.launch(ThreeDSecureLifecycleObserver.java:39) 
    at com.braintreepayments.api.ThreeDSecureClient.startVerificationFlow(ThreeDSecureClient.java:423).   
    at com.braintreepayments.api.ThreeDSecureClient.access$400(ThreeDSecureClient.java:32)
    at com.braintreepayments.api.ThreeDSecureClient$6.onResult(ThreeDSecureClient.java:334)
    at com.braintreepayments.api.ConfigurationLoader.loadConfiguration(ConfigurationLoader.java:41)
    at com.braintreepayments.api.BraintreeClient$1.onAuthorizationResult(BraintreeClient.java:183)
    at com.braintreepayments.api.AuthorizationLoader.loadAuthorization(AuthorizationLoader.java:20)
    at com.braintreepayments.api.BraintreeClient.getAuthorization(BraintreeClient.java:192)
    at com.braintreepayments.api.BraintreeClient.getConfiguration(BraintreeClient.java:179)
    at com.braintreepayments.api.ThreeDSecureClient.continuePerformVerification(ThreeDSecureClient.java:331)
    at com.braintreepayments.api.ThreeDSecureClient.continuePerformVerification(ThreeDSecureClient.java:260)
    at com.gopuff.features.payments.providers.threedsecure.ThreeDSecureNonceProvider$getThreeDSecureResult$1.invokeSuspend$lambda-0(ThreeDSecureNonceProvider.kt:92)
    at com.gopuff.features.payments.providers.threedsecure.ThreeDSecureNonceProvider$getThreeDSecureResult$1.$r8$lambda$R2DTCDskc4dt7gyI8INz-AWa-yA(Unknown Source:0)
    at com.gopuff.features.payments.providers.threedsecure.ThreeDSecureNonceProvider$getThreeDSecureResult$1$$ExternalSyntheticLambda0.onResult(Unknown Source:6)
    at com.braintreepayments.api.ThreeDSecureAPI$1.onResult(ThreeDSecureAPI.java:25)                                      
    at com.braintreepayments.api.HttpClient$2.run(HttpClient.java:123)
    at android.os.Handler.handleCallback(Handler.java:938)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loopOnce(Looper.java:201)
    at android.os.Looper.loop(Looper.java:288)
    at android.app.ActivityThread.main(ActivityThread.java:7839)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)

```
The crash happens not always and most likely depends on the payload that is transferred to the ThreeDSecureActivity within the extras.

**Comment by sshropshire** [comment] 2023-01-03 16:06
Hi @IgorButirsky thanks for using the Braintree SDK for Android. Is this reproducible every time the app attempts a 3DS transaction?

**Comment by IgorButirsky** [comment] 2023-01-04 09:23
Hi @sshropshire. No, this is not reproducible on each device. For example, I reproduced it on Pixel 7 Pro, but not on OnePlus 7 Pro. But if this crash happens on some devices, it happens all the time. Also, this issue probably depends on the bank. We were able to reproduce it for credit cards emitted by some European banks.

**Comment by sshropshire** [comment] 2023-01-04 22:01
@IgorButirsky ok. Are there any banks in particular? And if possible, could you reproduce the error and [set a breakpoint here](https://github.com/braintree/braintree_android/blob/6d5c4fd43dc88b57aa77728cb40f1703dba57393/ThreeDSecure/src/main/java/com/braintreepayments/api/ThreeDSecureAPI.java#L24) to inspect if the resulting JSON is abnormally large?

**Comment by IgorButirsky** [comment] 2023-01-05 21:44
@sshropshire, For us it was Universal Bank. 
Here is the screenshot: 
![Screenshot 2023-01-05 at 23 31 15](https://user-images.githubusercontent.com/1819603/210884915-1f251e88-1cd4-4d0d-a406-154bcee7522a.png)
In general, the resulting json looks fine except one value : 
```
{
    ...
    "lookup": {
        ...
        "pareq": "..."
    }
}
```
the `pareq` string is a way long - 339268 characters

**Comment by sshropshire** [comment] 2023-01-09 21:39
@IgorButirsky interesting. I'll reach out to Cardinal, our 3rd party MPI to see if this is a known issue.

**Comment by sshropshire** [comment] 2023-01-20 19:59
Hi @IgorButirsky would you mind providing the merchant id and a transaction id for one of these requests that's triggering the Android error? I can forward this to the appropriate team and they can take a more in depth look.

**Comment by hollabaq86** [comment] 2023-02-08 20:54
👋 @IgorButirsky If you can [contact Support](https://developer.paypal.com/braintree/help) referencing this issue, your merchant ID and a sample transaction ID, they can coordinate with the appropriate teams at PayPal/Braintree to investigate further. In the meantime, I'm going to go ahead and close this issue since it's been quiet for a few weeks.

**Comment by IgorButirsky** [comment] 2023-02-09 13:52
Hi @hollabaq86, the issue is still relevant, we moved the conversation to emails.

**Comment by sshropshire** [comment] 2023-02-09 15:21
@IgorButirsky we do have some internal tracking on this issue. Would you prefer us to re-open this for visibility?

**Comment by IgorButirsky** [comment] 2023-02-09 16:08
@sshropshire yeah, would be good.

**Comment by cltnschlosser** [comment] 2023-04-06 04:37
So it's nice that #711 prevents the crash from happening, but is there more to this than `The 3D Secure response returned is too large to continue. Please contact Braintree Support for assistance.`? How do we support these users that our trying to use our applications?
Is there anyway to make the transactions smaller, so that they don't hit this limit?

**Closed** 2023-04-06 14:26 UTC

**Comment by hollabaq86** [comment] 2023-04-11 20:18
Wanted to post one more update, our colleagues who own Braintree's API have updated their logic to screen for abnormally large sized responses like this so that they can cap the size and not send so much info that they crash merchant apps. 

This still doesn't resolve the source of these issues - the ACS provider - but we've added as much we can defensively to prevent these type exceptions

**Comment by hollabaq86** [comment] 2023-04-19 16:04
@cltnschlosser ack, I'd follow #724 for updates on this issue
