### ISSUE TITLE
Android: Two Factor Authentication accounts stuck when paypal app is installed

### ISSUE THREAD

**Issue by Bassem-Samy** [braintree/braintree_android#249] opened 2019-04-08 16:00 UTC
### General information

* SDK/Library version: 2.21.0
* Environment: Sandbox
* Android Version and Device: Any
* Braintree dependencies: 
com.braintreepayments.api:braintree:2.21.0

### Issue description
1. User has Android paypal app installed.
2. User tries to add paypal as a payment method using braintree sdk
3. Android Paypal app is opened user logs in and then waits for two factor authentication (sms in that case) 
4. After the user enters the correct sms code and successfully login, the screen goes blank, there's no activity result or anything.

so If a user has two factor authentication in their paypal account (sms for example) and has paypal app installed on their android device, when Adding payment method  using braintree sdk, after entering the sms code the screen goes blank and that's it.

I've reproduced it in a couple of already published apps on the playstore, the flow goes normally if the user doesn't have the android paypal app installed.

**Comment by quinnjn** [comment] 2019-04-08 16:27
Thanks for the report! We'll look into it and get back to you

**Comment by quinnjn** [comment] 2019-04-08 16:58
I was able to reproduce. 

It's not really a braintree_android issue though since we've handed the request off to the PayPal app, but I'll contact PayPal about the issue and go from there!

**Comment by Bassem-Samy** [comment] 2019-04-09 08:51
> I was able to reproduce.
> 
> It's not really a braintree_android issue though since we've handed the request off to the PayPal app, but I'll contact PayPal about the issue and go from there!

Thanks a lot! I hope it gets fixed soon!

**Comment by F9F8** [comment] 2019-07-09 08:04
I'm facing this problem too...

Something different:
- com.braintreepayments.api:braintree:3.1.0
- com.braintreepayments.api:data:1.7.10

Everything works perfect on SANDBOX, not PRODUCTION, after enters the code, the screen goes blank, if the paypal app isn't installed. 

On SANDBOX mode works, because perhaps it not used the paypal app, but the website.

**Comment by F9F8** [comment] 2019-07-09 11:08
After enter the code, see this exception from paypal

2019-07-09 13:05:15.447 21721-21721/? E/com.paypal.android.foundation.core.operations: exception: Attempt to invoke virtual method 'java.lang.String com.paypal.android.foundation.auth.model.Token.getTokenValue()' on a null object reference (java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.paypal.android.foundation.auth.model.Token.getTokenValue()' on a null object reference)
    java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.paypal.android.foundation.auth.model.Token.getTokenValue()' on a null object reference
        at com.paypal.android.foundation.auth.operations.ThirdPartySinglePaymentProxyOperation.completeThirdPartyOperation(SourceFile:37)
        at com.paypal.android.foundation.auth.operations.ThirdPartyProxyOperation$ThirdPartyOperationListener.a(SourceFile:57)
        at com.paypal.android.foundation.auth.operations.ThirdPartyProxyOperation$ThirdPartyOperationListener.onSuccess(SourceFile:52)
        at com.paypal.android.foundation.auth.operations.AuthenticationChallengeManager.authComplete(SourceFile:573)
        at com.paypal.android.foundation.auth.operations.AuthenticationChallengeManager.authComplete(SourceFile:551)
        at com.paypal.android.foundation.auth.operations.AuthenticationChallengeManager$1.onSuccess(SourceFile:498)
        at com.paypal.android.foundation.core.operations.Operation$1.call(SourceFile:51)
        at bolts.Task$3.run(SourceFile:195)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:216)
        at android.app.ActivityThread.main(ActivityThread.java:7238)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:575)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:909)

**Comment by scannillo** [comment] 2019-07-10 14:02
Hello @F9F8 . The issue at the origin of this thread was resolved by PayPal a bit ago. Also, interesting that you have success in Sandbox and not Production. I can't replicate this in Production for obvious reasons. 

Do you know if this always happening in Production for you, or only in certain situations? Also, is it only with 2FA enabled?

**Comment by F9F8** [comment] 2019-07-10 15:24
> * To clarify, is this happening with or without the PayPal app being installed?
**With the PayPal app.**
> * Is this always happening in Production for you, or only in certain situations?
**In production, installing PayPal and not logging in, 2FA enabled. 
(In Sandbox, i don't know how to enable 2FA)**
> * Is this only occurring with 2FA enabled?
**YES!**

Hi @scannillo , thank you for your quick reply. This problem occurs in the production, PayPal app installation and the situation of 2fa enabled. UBER app could replicate this problem.

1. Install PayPal app on device, keep it logging out (very important)! and make sure 2FA is enabled.
2. Open UBER app, try to add PayPal as a new payment method, after entering the code from sms, it will show a full white screen.

I have uploaded two videos which could help you to find it out.
[video1](https://www.dropbox.com/s/514ghn7390okxyv/VID_20190710162451.mp4?dl=0)
[video2](https://www.dropbox.com/s/ulvci53lq6tfgzf/VID_20190710_103711.mp4?dl=0)

**Comment by sestevens** [comment] 2019-07-10 21:09
Thanks for the additional info, @F9F8! Couple more questions for you:

1. Is the blank page you're seeing after entering the 2FA code appearing in the Uber app or the PayPal app? (It's a little hard to tell from the videos.)
2. Which version of the PayPal app do you have installed?

**Comment by F9F8** [comment] 2019-07-11 07:18
@scannillo The Page belongs to the PayPal app, the app version is 7.10.0, the current play store version. 

What's interesting is that, wenn i keep the PayPal app logging in, it works, because it will not trigger 2FA.

When the blank page comes, a NullPointerException is logged out.

2019-07-11 09:12:08.257 5010-5010/? E/com.paypal.android.foundation.core.operations: exception: Attempt to invoke virtual method 'java.lang.String com.paypal.android.foundation.auth.model.Token.getTokenValue()' on a null object reference (java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.paypal.android.foundation.auth.model.Token.getTokenValue()' on a null object reference)
    java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.paypal.android.foundation.auth.model.Token.getTokenValue()' on a null object reference
        at com.paypal.android.foundation.auth.operations.ThirdPartySinglePaymentProxyOperation.completeThirdPartyOperation(SourceFile:37)
        at com.paypal.android.foundation.auth.operations.ThirdPartyProxyOperation$ThirdPartyOperationListener.a(SourceFile:57)
        at com.paypal.android.foundation.auth.operations.ThirdPartyProxyOperation$ThirdPartyOperationListener.onSuccess(SourceFile:52)
        at com.paypal.android.foundation.auth.operations.AuthenticationChallengeManager.authComplete(SourceFile:573)
        at com.paypal.android.foundation.auth.operations.AuthenticationChallengeManager.authComplete(SourceFile:551)
        at com.paypal.android.foundation.auth.operations.AuthenticationChallengeManager$1.onSuccess(SourceFile:498)
        at com.paypal.android.foundation.core.operations.Operation$1.call(SourceFile:51)
        at bolts.Task$3.run(SourceFile:195)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:216)
        at android.app.ActivityThread.main(ActivityThread.java:7238)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:575)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:909)

**Comment by sestevens** [comment] 2019-07-11 18:01
@F9F8 Thanks for that information. It sounds like this is a bug in the PayPal Android app, not the `braintree_android` SDK. We'll let PayPal know so that they can investigate.

**Comment by sarahkoop** [comment] 2020-08-07 20:03
Closing due to inactivity. Also, adding a PayPal payment method now goes through a web browser.

**Closed by sarahkoop** 2020-08-07 20:03 UTC
