### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke virtual method 'void com.braintreepayments.api.internal.BraintreeHttpClient.get(java.lang.String, com.braintreepayments.api.interfaces.HttpResponseCallback)' on a null object reference

### ISSUE THREAD

**Issue by brunobar79** [braintree/braintree_android#105] opened 2016-06-07 06:51 UTC
Similar to #101 . Only on my release build (fresh install) I always get the following error:

`E/AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
Process: com.myapp, PID: 11127
java.lang.NullPointerException: Attempt to invoke virtual method 'void com.braintreepayments.api.internal.BraintreeHttpClient.get(java.lang.String, com.braintreepayments.api.interfaces.HttpResponseCallback)' on a null object reference
at com.braintreepayments.api.ConfigurationManager.getConfiguration(ConfigurationManager.java:50)
at com.braintreepayments.api.BraintreeFragment.fetchConfiguration(BraintreeFragment.java:482)
at com.braintreepayments.api.BraintreeFragment.waitForConfiguration(BraintreeFragment.java:528)
at com.braintreepayments.api.TokenizationClient.tokenize(TokenizationClient.java:38)
at com.braintreepayments.api.Card.tokenize(Card.java:29)
at com.myapp.braintree.Braintree.checkoutWithCreditCard(Braintree.java:100)
at java.lang.reflect.Method.invoke(Native Method)
...
...
...`

Any idea what's going on?
Thanks!

**Comment by lkorth** [comment] 2016-06-07 13:43
#101 is a different issue. This is caused by trying to create a payment method before the fragment has been attached to the activity. We're working on a fix for this.

**Closed** 2016-06-07 14:44 UTC

**Comment by lkorth** [comment] 2016-06-07 14:47
@brunobar79: thanks for the report. I've committed a fix that will go out in the next release.

If you'd like to be notified when new releases go out, please feel free to subscribe to our [Google Groups mailing list](https://groups.google.com/forum/#!forum/braintree-sdk-announce).
