### ISSUE TITLE
Phone number not coming in api response

### ISSUE THREAD

**Issue by Kelv** [braintree/braintree_android#505] opened 2022-01-26 14:07 UTC
I am using a PayPal Sandbox account, just debugged until reaching this Line here:https://github.com/braintree/braintree_android/blob/debd82965d4d3360c3e5f0d502f5d1db2d69810a/Braintree/src/main/java/com/braintreepayments/api/TokenizationClient.java#L96
But `responseBody` doesn't come with the phone number.

_Originally posted by @Kelv in https://github.com/braintree/braintree_android/issues/498#issuecomment-1021427966_

**Comment by sarahkoop** [comment] 2022-01-26 14:53
Hi @Kelv - Thanks for reporting this issue. We are investigating the cause and will post an update here when we have more information.

**Comment by sarahkoop** [comment] 2022-01-27 14:50
Our teams have identified and are working to resolve this issue. We will reach back out once this is fully resolved.

**Comment by jaxdesmarais** [comment] 2022-03-24 17:14
Hello @Kelv -

Hello @yburadkar and @dsmailes -

Apologies for the long delay on this. We were able to hear back from our internal team and they noted that there is a toggle to enable receiving the phone number. Because it is sensitive customer data, you have to opt-in to receiving it. You can enable it by following these steps:

1. Log into the Business Manager for your account. Sandbox URL: https://www.sandbox.paypal.com/mep/dashboard and Production: https://www.paypal.com/mep/dashboard
2. Hover over your name on the top right and click on "Account Settings"
3. Towards the bottom you will see a Products & Services section where you will click on "Website Payments"
4. Click on "update" next to Website preferences
5. Under Contact telephone number you will want to select either on - optional or on - mandatory

If it is optional and a customer does not provide their phone number, you would not receive one in the response. Once the toggle is enabled it may take up to 2 hours to begin receiving the phone number data. I was able to test this on my end and we are now seeing the phone number as expected, but please let me know if you run into issues.

**Comment by jaxdesmarais** [comment] 2022-03-29 13:57
Hello @Kelv - I am going to close out this issue as our testing indicates this has been resolved by following the steps above. If you continue to run into issues after following those steps, please feel free to reach back out and we would be happy to assist.

**Closed by jaxdesmarais** 2022-03-29 13:57 UTC
