### ISSUE TITLE
Error with authentication method with upgraded permissions

### ISSUE THREAD

**Issue by vakhileshwar** [braintree/braintree_android#627] opened 2022-11-25 13:25 UTC
Here is my code "

```
    braintreeClient = BraintreeClient(this, "sandbox_Tokenization_key")
    threeDSecureClient = ThreeDSecureClient(this,braintreeClient!!)
```

```
 threeDSecureClient!!.performVerification(
            this, threeDSecureRequest
        ) { threeDSecureResult: ThreeDSecureResult?, error: java.lang.Exception? ->
            if (threeDSecureResult != null) {
            } else {
              Error: Tokenization key authorization not allowed for this endpoint. Please use an authentication method with upgraded permissions
            }
        }
```

On invoking perform verification It throws error, says
**Tokenization key authorization not allowed for this endpoint. Please use an authentication method with upgraded permissions**

How can I  add authentication method with upgraded permissions, any help on this?
Can I have sample or documentation for this

**Comment by sshropshire** [comment] 2022-11-28 16:17
Closing as a duplicate of number #625.

**Closed by sshropshire** 2022-11-28 16:17 UTC
