### ISSUE TITLE
Paypal Sandbox payment just keeps redirecting me

### ISSUE THREAD

**Issue by breakline87** [braintree/braintree_android#220] opened 2018-07-30 18:31 UTC
Hello,

I implemented the basic PayPal one time checkout flow as described in the docs. However clicking on "Proceed with Sandbox Purchase" in the appearing window does nothing but just showing the same window again. Same with clicking on "Cancel purchase". Also, the window appears awfully slowly, taking several seconds.

My Activity:

`public class PaypalPaymentAcivity extends Activity implements PaymentMethodNonceCreatedListener {

    private BraintreeFragment mBraintreeFragment;

    @Override
    protected void onCreate(@Nullable Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_paypal);
        findViewById(R.id.payButton).setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                startPayment();
            }
        });
    }

    private void startPayment() {
        try {
            mBraintreeFragment = BraintreeFragment.newInstance(this, "eyJ2ZXJzaW9uIjoyLCJhdXRob3JpemF0aW9uRmluZ2VycHJpbnQiOiJlMjNmYTAzMDlkNTg0NTcxYjQ4MDMzNDlkZjNhYmY0Y2UxODVmNTUzNTYwZDBhODdlYzAyODE1YTZjYzdiOTZmfGNyZWF0ZWRfYXQ9MjAxOC0wNy0zMFQxNTowMjoyNi4xMjU0NTI4NjYrMDAwMFx1MDAyNm1lcmNoYW50X2lkPTM0OHBrOWNnZjNiZ3l3MmJcdTAwMjZwdWJsaWNfa2V5PTJuMjQ3ZHY4OWJxOXZtcHIiLCJjb25maWdVcmwiOiJodHRwczovL2FwaS5zYW5kYm94LmJyYWludHJlZWdhdGV3YXkuY29tOjQ0My9tZXJjaGFudHMvMzQ4cGs5Y2dmM2JneXcyYi9jbGllbnRfYXBpL3YxL2NvbmZpZ3VyYXRpb24iLCJjaGFsbGVuZ2VzIjpbXSwiZW52aXJvbm1lbnQiOiJzYW5kYm94IiwiY2xpZW50QXBpVXJsIjoiaHR0cHM6Ly9hcGkuc2FuZGJveC5icmFpbnRyZWVnYXRld2F5LmNvbTo0NDMvbWVyY2hhbnRzLzM0OHBrOWNnZjNiZ3l3MmIvY2xpZW50X2FwaSIsImFzc2V0c1VybCI6Imh0dHBzOi8vYXNzZXRzLmJyYWludHJlZWdhdGV3YXkuY29tIiwiYXV0aFVybCI6Imh0dHBzOi8vYXV0aC52ZW5tby5zYW5kYm94LmJyYWludHJlZWdhdGV3YXkuY29tIiwiYW5hbHl0aWNzIjp7InVybCI6Imh0dHBzOi8vb3JpZ2luLWFuYWx5dGljcy1zYW5kLnNhbmRib3guYnJhaW50cmVlLWFwaS5jb20vMzQ4cGs5Y2dmM2JneXcyYiJ9LCJ0aHJlZURTZWN1cmVFbmFibGVkIjp0cnVlLCJwYXlwYWxFbmFibGVkIjp0cnVlLCJwYXlwYWwiOnsiZGlzcGxheU5hbWUiOiJBY21lIFdpZGdldHMsIEx0ZC4gKFNhbmRib3gpIiwiY2xpZW50SWQiOm51bGwsInByaXZhY3lVcmwiOiJodHRwOi8vZXhhbXBsZS5jb20vcHAiLCJ1c2VyQWdyZWVtZW50VXJsIjoiaHR0cDovL2V4YW1wbGUuY29tL3RvcyIsImJhc2VVcmwiOiJodHRwczovL2Fzc2V0cy5icmFpbnRyZWVnYXRld2F5LmNvbSIsImFzc2V0c1VybCI6Imh0dHBzOi8vY2hlY2tvdXQucGF5cGFsLmNvbSIsImRpcmVjdEJhc2VVcmwiOm51bGwsImFsbG93SHR0cCI6dHJ1ZSwiZW52aXJvbm1lbnROb05ldHdvcmsiOnRydWUsImVudmlyb25tZW50Ijoib2ZmbGluZSIsInVudmV0dGVkTWVyY2hhbnQiOmZhbHNlLCJicmFpbnRyZWVDbGllbnRJZCI6Im1hc3RlcmNsaWVudDMiLCJiaWxsaW5nQWdyZWVtZW50c0VuYWJsZWQiOnRydWUsIm1lcmNoYW50QWNjb3VudElkIjoiYWNtZXdpZGdldHNsdGRzYW5kYm94IiwiY3VycmVuY3lJc29Db2RlIjoiVVNEIn0sIm1lcmNoYW50SWQiOiIzNDhwazljZ2YzYmd5dzJiIiwidmVubW8iOiJvZmYifQ==");
            PayPalRequest request = new PayPalRequest("1")
                    .currencyCode("USD")
                    .intent(PayPalRequest.INTENT_AUTHORIZE);
            PayPal.requestOneTimePayment(mBraintreeFragment, request);
        } catch (InvalidArgumentException e) {
            e.printStackTrace();
        }
    }

    @Override
    public void onPaymentMethodNonceCreated(PaymentMethodNonce paymentMethodNonce) {

    }
}`

In the Manifest:

`<activity android:name="com.braintreepayments.api.BraintreeBrowserSwitchActivity"
            android:launchMode="singleTask">
            <intent-filter>
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
                <data android:scheme="hu.appz4.iwelcome3.braintree" />
            </intent-filter>
        </activity>`

Can you help me with this? Is this something with the implementation? The package name is correct, and debugging does not give me any useful information

**Comment by quinnjn** [comment] 2018-07-31 20:25
It sounds like the problem is on the BrowserSwitch back into your app. You're confirming the payment / cancel but `BraintreeBrowserSwitchActivity` isn't getting the result.

Can you confirm that the scheme is setup correctly? You can directly copy the line provided in the [Browser Switch setup](https://developers.braintreepayments.com/guides/client-sdk/setup/android/v2#browser-switch-setup) docs. Gradle will fill in `${applicationId}` for you.
```
 <data android:scheme="${applicationId}.braintree" />
```

**Comment by breakline87** [comment] 2018-08-01 01:06
Hello,

unfortunately it's the same. I see this in Logcat, seems correct too (clicked on cancel):

`I/ActivityManager: START u0 {act=android.intent.action.VIEW cat=[android.intent.category.BROWSABLE] dat=hu.appz4.iwelcome3.braintree://onetouch/v1/cancel?token=EC-HERMES-SANDBOX-EC-TOKEN flg=0x10000000 cmp=hu.appz4.iwelcome3/com.braintreepayments.api.BraintreeBrowserSwitchActivity (has extras)} from uid 10041`

Or clicked on Proceed:

` I/ActivityManager: START u0 {act=android.intent.action.VIEW cat=[android.intent.category.BROWSABLE] dat=hu.appz4.iwelcome3.braintree://onetouch/v1/success?PayerID=HERMES-SANDBOX-PAYER-ID&token=EC-HERMES-SANDBOX-EC-TOKEN&paymentId=HERMES-SANDBOX-PAYMENT-ID flg=0x10000000 cmp=hu.appz4.iwelcome3/com.braintreepayments.api.BraintreeBrowserSwitchActivity (has extras)} from uid 10041`
    
    
Here is when the browser activity starts:

```
I/ActivityManager: START u0 {act=android.intent.action.VIEW dat=https://checkout.paypal.com/... flg=0x18008000 pkg=com.android.chrome cmp=com.android.chrome/com.google.android.apps.chrome.Main (has extras)} from uid 10506

I/ActivityManager: START u0 {act=android.intent.action.VIEW dat=customtab://6968b0a0-683a-4c20-89bf-0236247632bd?https://checkout.paypal.com/one-touch-login-sandbox/index.html?action=create_payment_resource&amount=1&authorization_fingerprint=e23fa0309d584571b4803349df3abf4ce185f553560d0a87ec02815a6cc7b96f%7Ccreated_at%3D2018-07-30T15%3A02%3A26.125452866%2B0000%26merchant_id%3D348pk9cgf3bgyw2b%26public_key%3D2n247dv89bq9vmpr&cancel_url=hu.appz4.iwelcome3.braintree%3A%2F%2Fonetouch%2Fv1%2Fcancel&controller=client_api%2Fpaypal_hermes&currency_iso_code=USD&experience_profile%5Baddress_override%5D=false&experience_profile%5Bbrand_name%5D=Acme+Widgets%2C+Ltd.+%28Sandbox%29&experience_profile%5Bno_shipping%5D=true&intent=authorize&merchant_id=348pk9cgf3bgyw2b&offer_paypal_credit=false&return_url=hu.appz4.iwelcome3.braintree%3A%2F%2Fonetouch%2Fv1%2Fsuccess&token=EC-HERMES-SANDBOX-EC-TOKEN&version=1&useraction= flg=0x18088000 pkg=com.android.chrome cmp=com.android.chrome/org.chromium.chrome.browser.customtabs.SeparateTaskCustomTabActivity (has extras)} from uid 10041
```

I will try it in an empty project, I'll let you know what happens

**Comment by quinnjn** [comment] 2018-08-01 19:49
That makes sense that `singleInstance` wouldn't work in this flow. If I understand correctly it wouldn't create new activities on top of it. Instead it would create a new activity task stack with `BrowserSwitchActivity`.

`BrowserSwitchActivity` depends on the activity stack having some activity to rely information back to. There would be no other activities in the stack so the results wouldn't be read.

I'm not to sure if it would be easy or possible to support `singleInstance` activities. Could you describe more detail on why you need `singleInstance` launch mode?

**Comment by breakline87** [comment] 2018-08-04 15:15
Hello,

thanks for the reply. So the problem can come when you integrate this into an existing app with a "singleInstance" activity. I have this problem and the original app wasn't made by me, and removing singleInstance might cause issues when the app uses the onNewIntent approach to communicate with the activity from subcomponents. I can circumvent the issue by having a separate activity for the payment though.

**Comment by jackellenberger** [comment] 2018-09-25 21:19
Hi @breakline87, I just wanted to close the loop on this - were you able to make a separate activity and solve the problem?

We haven't had any other reports to my knowledge of people having trouble with Braintree and singleInstance activities, but I also imagine that's a pretty small use case that may have issues. I'm going to close this for now unless you need help or we get another report.

**Closed by jackellenberger** 2018-09-25 21:19 UTC
