### ISSUE TITLE
CCInitProvider - Caused by java.lang.ClassNotFoundException

### ISSUE THREAD

**Issue by maxlooland** [braintree/braintree_android#355] opened 2021-04-03 12:09 UTC
### General information

* SDK/Library version: com.braintreepayments.api:drop-in:5.0.2
* Environment: Not environment-specific
* Target Sdk: 29
* Braintree dependencies:
            com.braintreepayments.api:braintree:3.15.0
            com.braintreepayments.api:drop-in:5.0.2
            com.braintreepayments.api:braintree:3.15.0
            com.braintreepayments.api:braintree:3.15.0
            com.braintreepayments.api:braintree:3.15.0
            com.braintreepayments.api:braintree:3.15.0

### Issue description

Hi, I recently updated the SDK from "3.7.1" to "5.0.2" and found crashes among users:

Caused by java.lang.ClassNotFoundException
Didn't find class "com.cardinalcommerce.shared.cs.utils.CCInitProvider" on path: DexPathList.....

Do you know anything about this problem?

**Comment by sshropshire** [comment] 2021-04-05 14:07
Hi @maxlooland thanks for using the Braintree SDK for Android.

Does upgrading to `com.braintreepayments.api:drop-in:5.2.0` resolve the issue? Cardinal Commerce is our third-party MPI provider and should be included as a transitive dependency of our Drop-in library.

**Comment by maxlooland** [comment] 2021-04-05 14:24
On the other hand, after updating to "com.braintreepayments.api:drop-in:5.2.0" - the problem is reproduced

**Comment by maxlooland** [comment] 2021-04-05 14:30
Yes, we have already tried the new version. In version "com.braintreepayments.api:drop-in:5.2.0" also reproduced

**Comment by sshropshire** [comment] 2021-04-05 14:41
@maxlooland that's interesting, the Cardinal Commerce dependency is listed [here](https://github.com/braintree/braintree-android-drop-in/blob/de66fe398b5de5b60adfb0b4f4262122e46e1659/Drop-In/build.gradle#L63) as an `api` dependency, so it should propagate into your app's dependencies. You may have to authenticate with Cardinal Commerce in order to fetch the dependency. In [this section](https://developers.braintreepayments.com/guides/3d-secure/client-side/android/v3#generate-a-client-token) of our dev guide, we show how to add cardinal credentials to your app's top-level Gradle file.

**Comment by nikitin-da** [comment] 2021-04-05 17:54
Hi @sshropshire, 
Of course we've added [these credentials](https://developers.braintreepayments.com/guides/3d-secure/client-side/android/v3#generate-a-client-token).
We've met ClassNotFoundException in runtime on certain users
Without cardinalcommerce credentials I believe we couldn't even sync the project

**Comment by sshropshire** [comment] 2021-04-05 18:38
@nikitin-da right had to ask for good measure. Could proguard be a factor here?

**Comment by nikitin-da** [comment] 2021-04-06 07:52
@sshropshire Looks like CCInitProvider is added to exceptions
Because we can see it without renaming in the obfuscated build
<img width="470" alt="Снимок экрана 2021-04-01 в 10 02 02" src="https://user-images.githubusercontent.com/7294857/113677229-06667100-96c6-11eb-8b13-31fbc144576c.png">

**Comment by sshropshire** [comment] 2021-04-06 14:28
@nikitin-da I see. Is this probably common on your local workstations as well? Also, is there additional information about the crashes observed in the user crash reports like device, Android version, etc.?

**Comment by nikitin-da** [comment] 2021-04-07 10:10
@sshropshire 
>Is this common on your local workstations as well?

No, we can see these crashes in Firebase only.
192 crash events affecting 95 users: all devices are Sumsung on Android 10

<img width="472" alt="Screenshot 2021-04-07 at 13 08 59" src="https://user-images.githubusercontent.com/7294857/113849722-71857580-97a2-11eb-872b-dba1334af2fe.png">

**Comment by sshropshire** [comment] 2021-04-08 14:31
@nikitin-da that is odd. I wonder if the issue could be with Samsung. I don't see any reason why `CCInitProvider` would not be present at runtime since the `three-d-secure` dependency is present. Is there a Samsung phone available on your end to help reproduce?

**Comment by nikitin-da** [comment] 2021-04-22 09:22
>Is there a Samsung phone available on your end to help reproduce?
Hi @sshropshire we found similar device but didn't reproduce the crash. As I can see in crashlytics, the number of crashes has decreased. Probably Sumsung has released some fix

**Comment by sarahkoop** [comment] 2021-09-17 16:57
Hi @nikitin-da - Closing this since it sounds like this issue has been resolved by Samsung. Please feel free to re-open if the issue persists.

**Closed by sarahkoop** 2021-09-17 16:57 UTC
