### ISSUE TITLE
BraintreeCancelListener is not called second time.

### ISSUE THREAD

**Issue by Jibs15** [braintree/braintree_android#330] opened 2021-02-22 07:30 UTC
`void onCancel(int requestCode)` of `BraintreeCancelListener` is called only first time. After cancelling for the first time, when the user cancels again `BraintreeCancelListener` is never triggered. It was working fine until I updated from `'com.braintreepayments.api:braintree:3.4.2'` to `'com.braintreepayments.api:braintree:3.15.0' `due to _Unsafe implementation of the HostnameVerifier interface - Google policy violation_ which is fixed in `'com.braintreepayments.api:braintree:3.15.0'`

**Comment by sshropshire** [comment] 2021-02-22 15:13
Hi @Jibs15 thanks for using the Braintree SDK for Android. This should be expected behavior when a browser switch has occurred and the user returns back to the application immediately. At this point, we consider the action to be canceled.

**Comment by Jibs15** [comment] 2021-02-22 15:22
Correct. This is exactly what I am expecting- works fine first time. When I again switch back to sandbox.paypal page and cancel in order to switch browser, BraintreeCancelListener never triggers.

**Comment by Jibs15** [comment] 2021-02-22 15:25
I understand this is an edge case but apparently it is raised as bug in my application since it was working alright in `'com.braintreepayments.api:braintree:3.4.2'`

**Comment by sshropshire** [comment] 2021-02-22 15:25
Can you list the exact steps to help reproduce?

**Comment by Jibs15** [comment] 2021-02-22 15:39
Sure. 
1) I have a webview with a button to proceed to paypal page. 
2) Cancel the process when you are at the log in page. It will take back to the webview. - BraintreeCancelListener triggers. All post cancellation code executes. Works fine till here.
3) Repeat step 1 and 2 - BraintreeCancelListener is never triggered. 

![image](https://user-images.githubusercontent.com/77680630/108731085-7d87e180-752c-11eb-852f-464463b1c8c0.png)

**Comment by sshropshire** [comment] 2021-02-22 15:53
I haven't been able to reproduce in our demo applications at the moment. Are you using our `popup-bridge-android` library as well? Also does the deep-link target activity have a `launchMode` other than "standard"?

**Comment by Jibs15** [comment] 2021-02-22 16:07
No, we are not using `popup-bridge-android` library. The `launchMode` is set to `singleTask`.

**Comment by sshropshire** [comment] 2021-02-22 16:34
`singleTask` for your activity with the web view? or for `BraintreeBrowserSwitchActivity`?

**Comment by Jibs15** [comment] 2021-02-22 16:37
For both :D

**Comment by Jibs15** [comment] 2021-02-22 17:00
Sorry. For the activity containing webview is singleTop and for BraintreeBrowserSwitchActivity is singleTask.

**Comment by sshropshire** [comment] 2021-02-23 15:35
Thanks @Jibs15. Unfortunately, I'm having trouble reproducing. Maybe a video of the issue could help? Also Android version / device etc.

**Comment by Jibs15** [comment] 2021-02-23 20:01
The device is Pixel 3a XL,  **Android Version-11 (API-30)** 

https://user-images.githubusercontent.com/77680630/108900308-c4073a00-7619-11eb-92b3-f98063963bd2.mp4

**Comment by sshropshire** [comment] 2021-02-24 14:31
It's hard to determine the root cause of this issue since we are unable to reproduce. Are you be able to set a breakpoint at [this line](https://github.com/braintree/braintree_android/blob/7958ebdd787d44b2f9fc0777eb03fbd2c77fac1c/Braintree/src/main/java/com/braintreepayments/api/BraintreeFragment.java#L402) of the SDK in your app?

**Comment by Jibs15** [comment] 2021-02-25 14:58
Unfortunately I cannot. Those are jar files. I only have access to the public methods of BraintreeFragment file.

**Comment by Jibs15** [comment] 2021-03-01 10:28
I tried to add breakpoint on line 89 (screenshot attached). I got the following values.  
requestCode: 13591
Result code: 0
Type : paypal
I cannot really understand the root cause as well. For some reason when I click on "X" second time `void onCancel(int requestCode)` is not triggered. Like I mentioned in the issue description, it is working all good in `'com.braintreepayments.api:braintree:3.4.2'` 
  
<img width="1476" alt="Screenshot 2021-03-01 at 08 51 22" src="https://user-images.githubusercontent.com/77680630/109467594-b3b4ec00-7a6b-11eb-917a-1341118da3fb.png">

**Comment by Jibs15** [comment] 2021-03-02 18:37
Hi @sshropshire
I finally found out that we were removing Braintreelisteners when `BraintreeCancelListener` is triggered under `onCancel(int requestCode)`
Do we have to explicitly remove the listeners or does the BraintreeFragment take care of it?

**Comment by sarahkoop** [comment] 2021-03-03 21:19
Hi @Jibs15, it depends how you are implementing the listener. If you are using `BraintreeFragment#addListener` to manage the listener yourself, then you should use `BraintreeFragment#removeListener` to clean up.  This section of the [developer documentation ](https://developers.braintreepayments.com/guides/client-sdk/setup/android/v3#register-listeners) provides more detail on registering listeners and may help with troubleshooting this issue.

**Comment by cbotsikas** [comment] 2021-06-19 02:13
We had to deal with this issue. It looks like only the first instance of `BraintreeFragment` that is created and added to the fragment manager is invoked when the app resumes using `BraintreeBrowserSwitchActivity` so in the end, there are no listeners to handle paypal response.
The solution we came up with was to remove the instance of `BraintreeFragment` from the manager after we remove it's listeners using `BraintreeFragment#removeListener` and by doing so, the correct fragment instance is invoked with the result and the listeners can handle it. 
```
            mBraintreeFragment.removeListener(this);
            mBraintreeFragment
                    .getParentFragmentManager()
                    .beginTransaction()
                    .remove(mBraintreeFragment)
                    .commit();
```
I've prepared for you a [demo repo](https://github.com/cbotsikas/BraintreeCancelListenerIssue) to test and reproduce the problem. The mentioned solution can be seen on a separate [commit](https://github.com/cbotsikas/BraintreeCancelListenerIssue/commit/e44fd12a17d8dfb005eb5682cbb0077e7c6b7c26)
In order to test this, you need to provide few clientTokens at [MainFragment.java#L64-L65](https://github.com/cbotsikas/BraintreeCancelListenerIssue/blob/master/app/src/main/java/com/example/braintreecancellistenerissue/ui/main/MainFragment.java#L64-L65) that will be used in rotation each time you click the paypal button. If you provide only one, it will always work, with or without the fix. Please provide two or more tokens in order to see the issue. On the real app, every time the user is invoking paypal, a new client token is generated. Comment out the lines [PaypalClient.java#L41-L45](https://github.com/cbotsikas/BraintreeCancelListenerIssue/blob/master/app/src/main/java/com/example/braintreecancellistenerissue/PaypalClient.java#L41-L45) to see the problem.

Hope this helps. Here are some screenshots:

![Without the fix](https://user-images.githubusercontent.com/1640100/122627907-fd752100-d0b2-11eb-9b66-41ddfda77510.png)
![With the fix](https://user-images.githubusercontent.com/1640100/122627910-ffd77b00-d0b2-11eb-90cb-cb4f22b24ff3.png)
![Adding clientTockens](https://user-images.githubusercontent.com/1640100/122627911-02d26b80-d0b3-11eb-8fb3-65a7db238ec7.png)

**Comment by sarahkoop** [comment] 2021-09-23 21:16
Hi @Jibs15 - We've released v4 of the SDK that uses a callback pattern rather than listeners and should resolve this issue. Please upgrade to the latest version of the SDK (`4.6.0`). Closing this - but please reopen of you are still experiencing the issue.

**Closed by sarahkoop** 2021-09-23 21:16 UTC
