### ISSUE TITLE
Feature module support

### ISSUE THREAD

**Issue by yenkenobi** [braintree/braintree_android#205] opened 2018-05-21 18:57 UTC
### General information

We are currently supporting an instant app which requires our project to be organized by feature modules. We are able to use the braintree sdk by including the dependency in our base feature module, but we are looking for ways to reduce our base feature apk size. Since our checkout feature is in a separate module, we are wanting to move the dependency from the base to the separate feature module.

* SDK/Library version: 2.13.0
* Environment: sandbox
* Android Version and Device: any device with API level 21+ that supports Instant Apps
* Braintree dependencies:
com.braintreepayments.api:braintree:2.13.0

### Issue description

Moving the braintree dependency downstream to the feature module, we get this error upon compilation:

`AAPT: error: resource style/bt_transparent_activity (aka com.hollar.android:style/bt_transparent_activity) not found`

Is there a way where we can make this work? I’ve tried copying the style from inside the project and while it compiled fine, I was unable to retrieve any payments via Google Pay.

**Comment by sdcoffey** [comment] 2018-05-21 23:17
Hey @yenkenobi,

Thanks for submitting this detailed bug report! I'll try to reproduce this issue, in the meantime can you verify that you're getting called back with a `BraintreeException` in your `BraintreeErrorListener` with the following message: `GooglePaymentActivity was not found in the Android manifest, or did not have a theme of R.style.bt_transparent_activity`?

**Comment by sdcoffey** [comment] 2018-05-22 17:54
To follow up, I was able to reproduce this issue. Based on [the instant app FAQ](https://developer.android.com/topic/google-play-instant/faqs), resources must be present in the base module.

> In addition, all the resources referenced by the manifest of a feature module must be present in the base feature module.

Since Braintree bundles some of its own resources, it seems like there's no way around adding Braintree as a dependency of your base module for the time being. 

If you're super concerned about the size of the the Braintree lib, and are only using it for Google Pay (which is the only payment method supported in Instant apps), I'd recommend forking this repo and pulling everything out that you don't need. Happy to provide guidance or answer questions about that if you have any. I'm going to close this issue, feel free to comment if you feel there's an aspect of this issue that I've missed.

**Closed by sdcoffey** 2018-05-22 17:54 UTC
