### ISSUE TITLE
UserCanceledException is not thrown when the user exits Chrometab web-flow

### ISSUE THREAD

**Issue by asos-edgeorge** [braintree/braintree_android#766] opened 2023-08-08 11:27 UTC
### Braintree SDK Version

4.36.0

### Environment

Both

### Android Version & Device

Google Pixel 3a XL - Android 13

### Braintree dependencies

* com.braintreepayments.api:paypal
* com.braintreepayments.api:local-payment

### Describe the bug

When launching a ChromeTab via a method that initiated the browser switch flow (e.g. `LocalPaymentClient#approveLocalPayment(FragmentActivity, LocalPaymentResult)`), cancelling the browser flow via the device's back button or ChromeTab's 'X' close button does not provide a callback to the app with the expected `UserCanceledException` on a provided `LocalPaymentListener` 

We believe that in v3 of the SDKs we were able to get a cancellation callback when the user quit at this stage previously 

### To reproduce

As described, create a basic payment flow in which a listener (e.g. `LocalPaymentListener`) is set and the `onLocalPaymentFailure` method logs when a `UserCanceledException` is returned

When calling a method that initiated the browser switch flow (e.g. `LocalPaymentClient#approveLocalPayment(FragmentActivity, LocalPaymentResult)`), manually cancel the browser flow via the device's back button or ChromeTab's 'X' close button

Observe no callback is made to the `LocalPaymentListener`

### Expected behavior

When the user dismisses the browser before the e2e flow is complete, we would expect listeners (e.g. `LocalPaymentListener`) to receive a `UserCanceledException` via relevant failure methods such as `onLocalPaymentFailure`

**Comment by sshropshire** [comment] 2023-08-08 14:34
Hi @asos-edgeorge thanks for using the Braintree SDK for Android. A `UserCanceledException` should be delivered when the merchant app enters the foreground without completing the Local Payment flow.

If possible, can you set a breakpoint [here in LocalPaymentClient.java](https://github.com/braintree/braintree_android/blob/master/LocalPayment/src/main/java/com/braintreepayments/api/LocalPaymentClient.java#L208) to see if the listener code is being triggered when you execute the steps to reproduce?

**Comment by asos-edgeorge** [comment] 2023-08-09 08:40
@sshropshire Thanks for your quick response  
  
I am seeing some IDE issues in that the sources do not match the bytecode when setting breakpoints in the `LocalPaymentClient` code, but I am 99.9% sure I am **not** seeing the listener code at the line you provided being triggered.

**Comment by sshropshire** [comment] 2023-08-09 14:46
Ok what about here in [LocalPaymentLifecycleObserver.java](https://github.com/braintree/braintree_android/blob/bbb34dc15e221aa0b1da55aebc14f6529f4e8de4/LocalPayment/src/main/java/com/braintreepayments/api/LocalPaymentLifecycleObserver.java#L28)? Also can you share how you're instantiating `LocalPaymentClient` in your host Fragment / Activity, and in which lifecycle method you do so (e.g. `onCreate()`)?

**Comment by asos-edgeorge** [comment] 2023-08-11 12:17
We aren't using a singleton `LocalPaymentClient`, but instead construct it when it's needed - so it isn't in a lifecycle method

```kotlin
private inline fun withLocalPaymentClient(token: String, block: LocalPaymentClient.(FragmentActivity) -> Any) {
        val fragment = getPaymentFragment()
        val activity = fragment.requireActivity()
        LocalPaymentClient(fragment, fragment.generateBraintreeClient(token)).run {
            block(activity)
        }
    }
```

We do see the lifecycle methods reporting correctly for `LocalPaymentLifecycleObserver` and the break point is hit for each lifecycle method

**Comment by sshropshire** [comment] 2023-08-11 15:10
Got it. From my perspective your integration sounds standard. The `listener` must also be set on `LocalPaymentClient` in order to receive the result from a browser switch. I would step through in `LocalPaymentLifecycleObserver` to see if `LocalPaymentClient#onBrowserSwitchResult()` is called, and to make sure the client notifies its listener via `onLocalPaymentSuccess()`.

**Comment by asos-edgeorge** [comment] 2023-08-24 08:35
Just to update here - I don't believe the callbacks are called, which I suspect is a bug. Would it be possible to be notified when the user exits the ChromeTab in the browser switch flow in a future release?

**Comment by sshropshire** [comment] 2023-08-24 19:58
@asos-edgeorge unfortunately there isn't a way to get a notification for a close event through the Chrome Custom Tabs API that I'm aware of. Is it possible for your app to instantiate the `LocalPaymentClient` in `onCreate()` like we mention in our [migration guide](https://github.com/braintree/braintree_android/blob/master/v4.9.0%2B_MIGRATION_GUIDE.md#client-token-provider)?

**Comment by tdchow** [comment] 2024-07-24 16:51
Hey @asos-edgeorge! We just released a beta for the next major version, v5.

In this version, the interface has been updated to give the additional browser switch flexibility. We'd love for you to try out the new version and see if the new integration pattern resolves the original browser switch cancel issue.

v5 Local Payment Migration Guide: https://github.com/braintree/braintree_android/blob/main/v5_MIGRATION_GUIDE.md#local-payment
v5 Release: https://github.com/braintree/braintree_android/releases/tag/5.0.0-beta1

**Comment by tdchow** [comment] 2024-10-01 15:36
Hi @asos-edgeorge  - Just wanted to keep you in the loop - we just released the GA version of v5!

Releases: https://github.com/braintree/braintree_android/releases/tag/5.0.0
v5 Migration Guide: https://github.com/braintree/braintree_android/blob/main/v5_MIGRATION_GUIDE.md

**Comment by sarahkoop** [comment] 2024-11-14 15:20
Closing this since v5 is now available with increased flexibility for handling cancellations.

**Closed by sarahkoop** 2024-11-14 15:20 UTC
Labels: v5 candidate
