### ISSUE TITLE
BrowserSwitchResult "User canceled PayPal" even though it was success 

### ISSUE THREAD

**Issue by sreereddymenon** [braintree/braintree_android#588] opened 2022-08-30 12:50 UTC
### General information

* SDK/Library version:4.15.0
* Environment: Sandbox
* Android Version and Device: Android 12 and Google Pixel 3 
* Braintree dependencies:
     implementation 'com.braintreepayments.api:paypal:4.15.0'
        implementation 'com.braintreepayments.api:venmo:4.15.0'
        implementation 'com.braintreepayments.api:data-collector:4.15.0'

### Issue description

I have a fragment

**Comment by sshropshire** [comment] 2022-08-30 14:12
Hi @sreereddymenon thanks for using the Braintree SDK for Android. Can you provide steps to reproduce this issue so we can diagnose futher?

It may also help to see a code snippet of your app's `PayPalClient` creation to help find the root cause of the false cancelation.

**Comment by Hector1990** [comment] 2022-10-18 12:42
I think this can be reproduced by:
1.  Complete the payment in paypal page, don't back to the app by deeplink.
2. Return to their app by switching manually.

**Comment by sshropshire** [comment] 2022-10-20 15:29
Thanks @Hector1990. Can you provide a video showing the issue? The deep link should automatically bring you back to the application after completing the PayPal flow.

**Comment by Hector1990** [comment] 2022-11-03 07:15
I provided the video here: https://github.com/braintree/braintree_android/issues/611

**Comment by sshropshire** [comment] 2022-11-14 19:52
@Hector1990 thanks that video is for the popup dialog. This seems to be a separate issue where the user isn't automatically redirected back to the application? Would you consider this a duplicate of #611?

**Comment by Hector1990** [comment] 2022-11-15 07:24
@sshropshire Sorry for that. They are two issues. I provided the video because if the deep link is not triggered automatically, you can manually switch to your app. And if your activity is not `singleTop` or `singleTask`, the canceled result he mentioned would be triggered.

**Comment by sshropshire** [comment] 2023-03-01 17:53
Hi @Hector1990 does this issue still occur in the latest [4.26.1](https://github.com/braintree/braintree_android/blob/master/CHANGELOG.md#4261) version?

**Comment by Chaos2805** [comment] 2023-08-21 06:12
@sshropshire I hit it in latest drop in version  - 6.11.0, which include 4.33.0

**Comment by liucaizhong** [comment] 2024-06-26 09:10
Are there any updates for this feature?  @sshropshire @sarahkoop 
Some GA merchants think if automatic redirection is not realized, it will impact the conversion rate.

**Comment by tdchow** [comment] 2024-10-01 15:35
Hi all - We just released the GA version of v5! In this version, the interface has been updated to give the additional browser switch flexibility. Would you be able to try out v5 and see if the issue is resolved?

Releases: https://github.com/braintree/braintree_android/releases/tag/5.0.0
v5 Migration Guide: https://github.com/braintree/braintree_android/blob/main/v5_MIGRATION_GUIDE.md

**Comment by sarahkoop** [comment] 2024-11-14 15:16
Closing this since v5 is now available with increased flexibility for handling cancellations.

**Closed by sarahkoop** 2024-11-14 15:16 UTC
Labels: v5 candidate
