### ISSUE TITLE
Chrome tab remains open in background when pay with paypal

### ISSUE THREAD

**Issue by straltest** [braintree/braintree_android#244] opened 2019-02-15 12:52 UTC
### General information

* SDK/Library version: 2.+
* Environment: Sandbox
* Android Version and Device: Motorola Moto G4 plus with Android 7.0
* Braintree dependencies: 
com.braintreepayments.api:braintree:2.+

Android : 
minSdkVersion 21
targetSdkVersion 27
compileSdkVersion 27

### Issue description

I am working on flutter application. I have made plugin to pay with paypal. I can able to pay successfully using paypal and returning to my application but paypal tab still remains in background and it is not destroyed.

I have also tried using 'com.braintreepayments.api:braintree:3.0.0' but still facing same issue. 

I have also downloaded https://github.com/quinnjn/braintree-android-drop-in-paypal-androidx this demo from this link https://github.com/braintree/braintree-android-drop-in/issues/101. Run it in Android simulator API level 28 but same issue is occurring.

Here is my code : 

try {
      mBraintreeFragment = BraintreeFragment.newInstance(this, tokenizationkey);
} catch (InvalidArgumentException e) {
      Log.d(getClass().getSimpleName(), e.getLocalizedMessage());
}
PayPal.requestOneTimePayment(mBraintreeFragment, getPayPalRequest(amount));

private PayPalRequest getPayPalRequest(@Nullable String amount) {
    PayPalRequest request = new PayPalRequest(amount);
    request.currencyCode("EUR");
    return request;
  }

@Override
  public void onPaymentMethodNonceCreated(PaymentMethodNonce paymentMethodNonce) {
    Log.d(getClass().getSimpleName(), "Payment Method Nonce received: " + paymentMethodNonce.getNonce());
  }

After successful payment I am getting nonce and returning to application. Chrome paypal tab not destroyed.

Requesting help to resolve this issue. Let me know if anything I am missing.

**Comment by Epreuve** [comment] 2019-02-15 13:47
Hey @straltest thanks for the report.  This is actually an issue with Chrome Custom Tabs in that there currently isn't a way to programatically close a tab.  

There is an open issue for Chromium [here](https://bugs.chromium.org/p/chromium/issues/detail?id=925539&q=component%3AUI%3EBrowser%3EMobile%3ECustomTabs&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified) that we've weighed in on, in hopes that they will add a method for us to use to resolve this.  Unfortunately at current, this is expected behavior.

We will leave this issue open so we can update you or anyone else that comes across this issue with any updates based on the Chromium issue above.

**Comment by straltest** [comment] 2019-02-16 04:42
Hello, @Epreuve,
Thank you for your reply. Let me know about any updates regarding this in future.

**Comment by crazecdwn** [comment] 2019-04-05 02:57
I'll close all my tabs

**Comment by skauss** [comment] 2020-10-05 11:20
Same problem since 2019

**Comment by sarahkoop** [comment] 2021-03-08 22:22
Fixed in [4.0.0-beta1](https://github.com/braintree/braintree_android/releases/tag/4.0.0-beta1)

**Closed by sarahkoop** 2021-03-08 22:22 UTC
