### ISSUE TITLE
403 Forbidden - https://cardinalcommerce.bintray.com/android

### ISSUE THREAD

**Issue by auxDK** [braintree/braintree_android#360] opened 2021-04-12 18:48 UTC
### Issue description

Are these still valid credentials as we are currently receiving a 403 in our pipeline  when bundling our app.

```
maven {
        url "https://cardinalcommerce.bintray.com/android"
        credentials {
               username 'braintree-team-sdk@cardinalcommerce'
                password '220cc9476025679c4e5c843666c27d97cfb0f951'

        }
    }
```

**Comment by rameshkumarkhatri** [comment] 2021-04-12 19:18
Same here also, 


> 
> * What went wrong:
> Could not determine the dependencies of task ':app:compileReleaseSaharaKotlin'.
> > Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
>    > Could not resolve org.jfrog.cardinalcommerce.gradle:cardinalmobilesdk:2.2.4-1.
>      Required by:
>          project :app > com.braintreepayments.api:drop-in:5.2.0 > com.braintreepayments.api:three-d-secure:3.15.0
>       > Could not resolve org.jfrog.cardinalcommerce.gradle:cardinalmobilesdk:2.2.4-1.
>          > Could not get resource 'https://dl.bintray.com/guardian/android/org/jfrog/cardinalcommerce/gradle/cardinalmobilesdk/2.2.4-1/cardinalmobilesdk-2.2.4-1.pom'.
>             > Could not HEAD 'https://dl.bintray.com/guardian/android/org/jfrog/cardinalcommerce/gradle/cardinalmobilesdk/2.2.4-1/cardinalmobilesdk-2.2.4-1.pom'. Received status code 403 from server: Forbidden
>       > Could not resolve org.jfrog.cardinalcommerce.gradle:cardinalmobilesdk:2.2.4-1.
>          > Could not get resource 'https://cardinalcommerce.bintray.com/android/org/jfrog/cardinalcommerce/gradle/cardinalmobilesdk/2.2.4-1/cardinalmobilesdk-2.2.4-1.pom'.
>             > Could not HEAD 'https://cardinalcommerce.bintray.com/android/org/jfrog/cardinalcommerce/gradle/cardinalmobilesdk/2.2.4-1/cardinalmobilesdk-2.2.4-1.pom'. Received status code 403 from server: Forbidden

**Comment by sarahkoop** [comment] 2021-04-12 20:15
Hi @auxDK - The credentials have not changed. Have you added the credentials in a `repositories {}` block in your app-level build.gradle?  Additionally, which version of the SDK are you using?  Did you previously have a working integration or is this issue occurring on initial setup?

**Comment by Glaubenio** [comment] 2021-04-12 20:36
Same problem here, and it was building ok last week

**Comment by HungDo** [comment] 2021-04-12 20:41
I'm running into this issue as well but was fine last week. The credentials in 'repository{}' are in my app level build.gradle file.

SDK versions:
`implementation('com.braintreepayments.api:drop-in:4.5.0')
implementation 'com.braintreepayments.api:braintree:3.9.0'`

**Comment by sarahkoop** [comment] 2021-04-12 21:16
It looks like the 403 error may have been resolved. Can you confirm if the issue still exists?

**Comment by HungDo** [comment] 2021-04-12 22:41
> It looks like the 403 error may have been resolved. Can you confirm if the issue still exists?

I can confirm it works now

**Comment by auxDK** [comment] 2021-04-13 07:41
@sarahkoop  it works now

**Comment by auxDK** [comment] 2021-04-26 15:13
@sarahkoop   the issue appeared again
`   > Could not resolve org.jfrog.cardinalcommerce.gradle:cardinalmobilesdk:2.2.5-1.
     Required by:
         project : > project :checkout > com.braintreepayments.api:three-d-secure:3.16.1
      > Could not resolve org.jfrog.cardinalcommerce.gradle:cardinalmobilesdk:2.2.5-1.
         > Could not get resource 'https://cardinalcommerce.bintray.com/android/org/jfrog/cardinalcommerce/gradle/cardinalmobilesdk/2.2.5-1/cardinalmobilesdk-2.2.5-1.pom'.
            > Could not GET 'https://cardinalcommerce.bintray.com/android/org/jfrog/cardinalcommerce/gradle/cardinalmobilesdk/2.2.5-1/cardinalmobilesdk-2.2.5-1.pom'. Received status code 403 from server: Forbidden`

**Comment by snitsaruk** [comment] 2021-04-27 08:18
Hello, @braintreeps, @sarahkoop. Any plans on fixing this?
JCenter will be completely out of service on May 1st, 2021.
This requires immediate action.

**Comment by sarahkoop** [comment] 2021-04-27 14:16
It appears that Bintray status is back to operational. We are aware of the upcoming sunset of Bintray and are awaiting updated credentials from the third-party provider. We will provide an update when we have additional information.

**Comment by sarahkoop** [comment] 2021-04-30 18:53
Closing this for now. Please use #373 for additional comments.

**Closed by sarahkoop** 2021-04-30 18:53 UTC

**Comment by talha32022** [comment] 2021-05-02 23:31
hi when i am trying to build my app I am receiving this error code 
**Could not GET 'https://cardinalcommerce.bintray.com/android/org/jfrog/cardinalcommerce/gradle/cardinalmobilesdk/2.2.4-1/cardinalmobilesdk-2.2.4-1.aar'. Received status code 403 from server: Forbidden**

**Comment by AnastasiyaVia** [comment] 2021-05-03 07:11
Same issue 
Please help

**Comment by mtrakal** [comment] 2021-05-03 07:15
**JCenter/Bintray shutdown:** https://github.com/braintree/braintree_android/issues/373
