### ISSUE TITLE
NPE on CardinalMobileSDK

### ISSUE THREAD

**Issue by stwonary** [braintree/braintree_android#470] opened 2021-11-03 17:42 UTC
### General information

* SDK/Library version: 3.18.0
* Environment: Production
* Android Version and Device: Android 9, Android 10 and Android 11
Top devices:  Xiaomi Mi 11 Lite, Samsung Galaxy A21s, Huawei HUAWEI Mate 20 lite, Xiaomi Mi 10T
* Braintree dependencies:
```
implementation 'com.braintreepayments.api:braintree:3.18.0
```

### Issue description

After update the SDK version to 3.18.0 we start detecting random crashes on Production.

```
java.lang.RuntimeException:
  at android.app.ActivityThread.performLaunchActivity (ActivityThread.java:3539)
  at android.app.ActivityThread.handleLaunchActivity (ActivityThread.java:3699)
  at android.app.servertransaction.LaunchActivityItem.execute (LaunchActivityItem.java:85)
  at android.app.servertransaction.TransactionExecutor.executeCallbacks (TransactionExecutor.java:135)
  at android.app.servertransaction.TransactionExecutor.execute (TransactionExecutor.java:95)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:2135)
  at android.os.Handler.dispatchMessage (Handler.java:106)
  at android.os.Looper.loop (Looper.java:236)
  at android.app.ActivityThread.main (ActivityThread.java:8037)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:656)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:967)
Caused by: java.lang.NullPointerException:
  at com.cardinalcommerce.cardinalmobilesdk.a.a.a.a (a.java:302)
  at com.cardinalcommerce.cardinalmobilesdk.Cardinal.cca_continue (Cardinal.java:2)
  at com.braintreepayments.api.ThreeDSecureActivity.onCreate (ThreeDSecureActivity.java:38)
  at android.app.Activity.performCreate (Activity.java:8141)
  at android.app.Activity.performCreate (Activity.java:8113)
  at android.app.Instrumentation.callActivityOnCreate (Instrumentation.java:1310)
  at android.app.ActivityThread.performLaunchActivity (ActivityThread.java:3512)
  at android.app.ActivityThread.handleLaunchActivity (ActivityThread.java:3699)
  at android.app.servertransaction.LaunchActivityItem.execute (LaunchActivityItem.java:85)
  at android.app.servertransaction.TransactionExecutor.executeCallbacks (TransactionExecutor.java:135)
  at android.app.servertransaction.TransactionExecutor.execute (TransactionExecutor.java:95)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:2135)
  at android.os.Handler.dispatchMessage (Handler.java:106)
  at android.os.Looper.loop (Looper.java:236)
  at android.app.ActivityThread.main (ActivityThread.java:8037)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:656)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:967)

//----------------------------------------------------------------------

java.lang.NullPointerException:
  at com.cardinalcommerce.shared.cs.f.m.a (m.java:93)
  at com.cardinalcommerce.shared.cs.userinterfaces.ChallengeNativeView.a (ChallengeNativeView.java:13)
  at com.cardinalcommerce.shared.cs.userinterfaces.ChallengeNativeView.b (ChallengeNativeView.java)
  at com.cardinalcommerce.shared.cs.userinterfaces.ChallengeNativeView$6.onClick (ChallengeNativeView.java:359)
  at android.view.View.performClick (View.java:7862)
  at android.widget.TextView.performClick (TextView.java:15004)
  at android.view.View.performClickInternal (View.java:7831)
  at android.view.View.access$3600 (View.java:879)
  at android.view.View$PerformClick.run (View.java:29359)
  at android.os.Handler.handleCallback (Handler.java:883)
  at android.os.Handler.dispatchMessage (Handler.java:100)
  at android.os.Looper.loop (Looper.java:237)
  at android.app.ActivityThread.main (ActivityThread.java:8167)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:496)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1100)

//----------------------------------------------------------------------

java.lang.NullPointerException:
  at com.cardinalcommerce.shared.cs.f.m.a (m.java:93)
  at com.cardinalcommerce.shared.cs.userinterfaces.ChallengeNativeView.a (ChallengeNativeView.java:13)
  at com.cardinalcommerce.shared.cs.userinterfaces.ChallengeNativeView.b (ChallengeNativeView.java)
  at com.cardinalcommerce.shared.cs.userinterfaces.ChallengeNativeView$6.onClick (ChallengeNativeView.java:359)
  at android.view.View.performClick (View.java:7507)
  at android.view.View.performClickInternal (View.java:7484)
  at android.view.View.access$3600 (View.java:839)
  at android.view.View$PerformClick.run (View.java:28679)
  at android.os.Handler.handleCallback (Handler.java:938)
  at android.os.Handler.dispatchMessage (Handler.java:99)
  at android.os.Looper.loop (Looper.java:236)
  at android.app.ActivityThread.main (ActivityThread.java:8037)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:656)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:967)

//----------------------------------------------------------------------
```

**Comment by sshropshire** [comment] 2021-11-03 20:40
Hi @stwonary thanks for using the Braintree SDK for Android. We haven't updated cardinal since version [3.17.2](https://github.com/braintree/braintree_android/pull/471) was this happening in a previous version as well or only after updating to the latest `3.x` version?

**Comment by stwonary** [comment] 2021-11-10 04:21
you are right. but seems to be related with 3dsv2. because we rolled back to 3.17.2 but with 3dsv2 enabled and we are detecting some crashes

**Comment by sarahkoop** [comment] 2021-11-18 16:20
Hi @stwonary - We've released version `3.18.1` of the SDK with an updated Cardinal Mobile SDK version. Can you update and confirm if this resolves the crashes you are seeing?

**Comment by stwonary** [comment] 2021-11-29 06:55
Hi @sarahkoop  we still having crashes with the version 3.18.1. A bit different seems to be similar crash. What we can confirm is that only happening with users with 3ds v2


```
java.lang.RuntimeException: 
  at android.app.ActivityThread.performLaunchActivity (ActivityThread.java:3539)
  at android.app.ActivityThread.handleLaunchActivity (ActivityThread.java:3699)
  at android.app.servertransaction.LaunchActivityItem.execute (LaunchActivityItem.java:85)
  at android.app.servertransaction.TransactionExecutor.executeCallbacks (TransactionExecutor.java:135)
  at android.app.servertransaction.TransactionExecutor.execute (TransactionExecutor.java:95)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:2135)
  at android.os.Handler.dispatchMessage (Handler.java:106)
  at android.os.Looper.loop (Looper.java:236)
  at android.app.ActivityThread.main (ActivityThread.java:8056)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:656)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:967)
Caused by: java.lang.NullPointerException: 
  at com.cardinalcommerce.cardinalmobilesdk.a.a.a.a (a.java:318)
  at com.cardinalcommerce.cardinalmobilesdk.Cardinal.cca_continue (Cardinal.java:2)
  at com.braintreepayments.api.ThreeDSecureActivity.onCreate (ThreeDSecureActivity.java:38)
  at android.app.Activity.performCreate (Activity.java:8143)
  at android.app.Activity.performCreate (Activity.java:8115)
  at android.app.Instrumentation.callActivityOnCreate (Instrumentation.java:1310)
  at android.app.ActivityThread.performLaunchActivity (ActivityThread.java:3512)
  at android.app.ActivityThread.handleLaunchActivity (ActivityThread.java:3699)
  at android.app.servertransaction.LaunchActivityItem.execute (LaunchActivityItem.java:85)
  at android.app.servertransaction.TransactionExecutor.executeCallbacks (TransactionExecutor.java:135)
  at android.app.servertransaction.TransactionExecutor.execute (TransactionExecutor.java:95)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:2135)
  at android.os.Handler.dispatchMessage (Handler.java:106)
  at android.os.Looper.loop (Looper.java:236)
  at android.app.ActivityThread.main (ActivityThread.java:8056)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:656)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:967)
```

**Comment by sarahkoop** [comment] 2021-11-29 15:49
Hi @stwonary - Since version `3.18.1` uses the latest Cardinal Mobile SDK, we will have to bring this issue to them for more investigation. If you could provide steps to reproduce and a video demonstrating the crash, that would be very helpful!

**Comment by sarahkoop** [comment] 2022-01-10 16:20
Hi @stwonary - Wanted to post an update that we've reached out to Cardinal about this, but without steps to reproduce it will be much more difficult to investigate. Are you able to provide steps to reproduce?

**Comment by Pirokar** [comment] 2022-02-02 11:14
@sarahkoop The same error with 3.19.0 when trying to get checkout with Braintree.

E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.ocado.mobile.android.dev, PID: 29522
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.ocado.mobile.android.dev/com.braintreepayments.api.ThreeDSecureActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.cardinalcommerce.cardinalmobilesdk.a.a.f.b()' on a null object reference
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4031)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4197)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2434)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:226)
        at android.os.Looper.loop(Looper.java:313)
        at android.app.ActivityThread.main(ActivityThread.java:8633)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1133)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.cardinalcommerce.cardinalmobilesdk.a.a.f.b()' on a null object reference
        at com.cardinalcommerce.cardinalmobilesdk.a.a.a.a(Unknown Source:326)
        at com.cardinalcommerce.cardinalmobilesdk.Cardinal.cca_continue(Unknown Source:2)
        at com.braintreepayments.api.ThreeDSecureActivity.onCreate(ThreeDSecureActivity.java:33)
        at android.app.Activity.performCreate(Activity.java:8282)
        at android.app.Activity.performCreate(Activity.java:8262)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1329)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4005)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4197) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2434) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loopOnce(Looper.java:226) 
        at android.os.Looper.loop(Looper.java:313) 
        at android.app.ActivityThread.main(ActivityThread.java:8633) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1133)

**Comment by stwonary** [comment] 2022-04-06 15:46
Hi @sarahkoop  our migration to 4.x is still WIP. meanwhile can you upgrade it on the 3.x as well?  thank you

**Comment by crookedneighbor** [comment] 2022-08-08 20:15
Looks like this is closed in https://github.com/braintree/braintree-android-drop-in/issues/338

**Comment by sshropshire** [comment] 2022-08-18 15:36
Hi @stwonary gathering more information on this issue. Is this 100% reproducible in your application or does it occur infrequently?

**Comment by stwonary** [comment] 2022-08-19 21:32
Hi, I was able to reproduce this error and got this error log


> E/AndroidRuntime(22488): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.touwolf.cllappmovil/com.braintreepayments.api.ThreeDSecureActivity}: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.


and fix it by add one line the AndroidManifest.xml

```
<application
      android:theme="@Theme.AppCompat.Light.NoActionBar"
  >
```

**Comment by sshropshire** [comment] 2022-08-23 16:03
> \<application android:theme="@Theme.AppCompat.Light.NoActionBar"\>

@stwonary this is the best solution. For now it's a limitation with our 3rd-party MPI since they don't return a result via the Android activity result API. Closing for now.

**Closed by sshropshire** 2022-08-23 16:03 UTC
Labels: awaiting input

**Comment by caruspi** [comment] 2022-08-30 08:03
Hi @stwonary, please, could you describe us how do you reproduce the crash? Could you reproduce the crash with the BrainTree sample app?
We are facing a similar crash but we are unable to reproduce it.

**Comment by stwonary** [comment] 2022-08-30 20:36
Hi @caruspi  

try to pay with a Visa and 3ds version 2 with OTP verification. the one that shows a webview and ask the user to put a OTP or MFA.
