### ISSUE TITLE
Android Braintree SDK 3.5.0 not building project

### ISSUE THREAD

**Issue by GalatiaPar** [braintree/braintree_android#266] opened 2019-09-04 07:41 UTC
### General information

* SDK/Library version: 3.5.0
* Environment: Sandbox for now
* Android Version and Device: Doesn't matter. Build issue
* Braintree dependencies: 
'com.braintreepayments.api:braintree:3.5.0'
'com.braintreepayments.api:three-d-secure:3.5.0'

### Issue description
I have a Gradle file that syncs and a project that builds normally. Once I add the braintree dependencies, the project can't sync showing me this error:

"ERROR: Failed to resolve: org.jfrog.cardinalcommerce.gradle:cardinalmobilesdk:2.1.4-1"

I added the following to overcome this issue as I read from people having the same issue that it's the solution:

```
maven {
            url  "https://cardinalcommerce.bintray.com/android"
            credentials {
                username 'braintree-team-sdk@cardinalcommerce'
                password '220cc9476025679c4e5c843666c27d97cfb0f951'
            }
        }
```

Then I get this issue:

"In project 'app' a resolved Google Play services library dependency depends on another at an exact version (e.g. "[1.3.1 ,2.3]", but isn't being resolved to that version. Behavior exhibited by the library will be unknown. 

Dependency failing: com.nimbusds:nimbus-jose-jwt:7.0.1 -> net.minidev:json-smart@[1.3.1,2.3], but json-smart version was
 2.3."

As a solution, I am adding the following

```
googleServices {
    disableVersionCheck = true
}
```

I no longer have this issue and my gradle syncs, but the project doesn't build with the error of "Manifest merger failed with multiple errors, see logs".

Can anyone help please?

**Comment by v-sulimov** [comment] 2019-09-04 13:19
@GalatiaPar 
I'm also facing the same issues and there is a little guide of how you can fix that.

First: Dependencies error

This happens because ThreeDSecure library depends on CardinalMobile SDK and CardinalMobile has some conflicting dependencies with Google Play Sevices. Disable version check isn't the best solution, this problem is documented on the CardinalMobile SDK website and also there is a proper way to fix that

See https://cardinaldocs.atlassian.net/wiki/spaces/CMSDK/pages/876052486/Android+Frequently+Asked+Questions

Section Error ' Dependency failing: com.nimbusds:nimbus-jose-jwt:5.1 -> net.minidev:json-smart@[1.3.1,2.3] '

About manifest: Same root of the problem. 3DS library defines one values for some parameters and you probably defined another value for the same parameters and a conflict occurs. You can fix that using tools: replace and specify conflicting parameters (for me it was allowBackup and supportsRtl). 

I hope I helped you. 
Best regards, Vitaly Sulimov.

**Comment by Epreuve** [comment] 2019-09-04 14:28
Hey @GalatiaPar as @v-sulimov pointed out, this is typically caused by the Google Services Plugin which has a bug as noted in [this issue[(https://github.com/google/play-services-plugins/issues/30), and we've worked with Cardinal to try to come up with the workaround they noted, which is documented in the Cardinal documentation.

Unfortunately until the Google plugin is updated with a bugfix, this work around or something similar will have to do to fix this, but we'll be keeping an eye on the issue as well.

If you can, please share the manifest errors and we can take a look at those and try to help get those resolved as well.

**Comment by sestevens** [comment] 2019-09-10 14:04
I'm going to close this issue. For anyone who lands here in the future, you may also want to take a look at our docs for [instructions on resolving this issue](https://developers.braintreepayments.com/guides/3d-secure/client-side/android/v3#generate-a-client-token).

**Closed** 2019-09-10 14:04 UTC
