### ISSUE TITLE
NullPointerException in AddPaymentMethodViewController

### ISSUE THREAD

**Issue by icaspi** [braintree/braintree_android#100] opened 2016-05-20 16:18 UTC
Hey,  

We are seeing the following crash in production, not sure what make of it:

```
Caused by java.lang.NullPointerException
       at com.braintreepayments.api.AddPaymentMethodViewController.initViews(AddPaymentMethodViewController.java:76)
       at com.braintreepayments.api.AddPaymentMethodViewController.(AddPaymentMethodViewController.java)
       at com.braintreepayments.api.BraintreePaymentActivity.initAddPaymentMethodView(BraintreePaymentActivity.java:280)
       at com.braintreepayments.api.BraintreePaymentActivity.showAddPaymentMethodView(BraintreePaymentActivity.java:271)
       at com.braintreepayments.api.BraintreePaymentActivity.onPaymentMethodNoncesUpdated(BraintreePaymentActivity.java:148)
       at com.braintreepayments.api.BraintreePaymentActivity.onCreate(BraintreePaymentActivity.java:120)
```
 
Looks like the CardForm is failing to initialize but I'm not sure why.

Cheers!

**Comment by sdcoffey** [comment] 2016-05-20 16:41
Hey @icaspi,

Thanks for bringing this up, and congrats on filing bug #100! What version of the SDK are you using? I'll take a look this morning.

**Comment by icaspi** [comment] 2016-05-20 17:10
@sdcoffey Not sure which version gradle is pointing to com.braintreepayments.api:braintree:2.+, com.braintreepayments.api:drop-in:2.+

**Comment by sdcoffey** [comment] 2016-05-20 20:37
Hey @icaspi,

Are you seeing this crash in the wild? This is a weird one. Basically, what's happening is that `BraintreeFragment`'s `Configuration` object is absent on creation of the `AddPaymentmethodViewController`, however, `AddPaymentMethodViewController` really can't be instantiated without a valid `Configuration`. Could be a GC timing issue, do you have any other information about the devices this crash is happening on?

**Comment by sdcoffey** [comment] 2016-05-24 21:41
Hey @icaspi,

Just wanted to check in, are you still seeing this issue?

**Comment by icaspi** [comment] 2016-05-25 00:31
Hey @sdcoffey 

I checked our logs again, it looks like that the app is in a real funny state (going up or down not sure) so it could be that the api is just a passenger in this accident

**Comment by sdcoffey** [comment] 2016-05-25 03:29
@icaspi, hm that's strange. I'm going to close this for now, then. Please reopen this issue if it rears its ugly head again.

**Comment by Duoblood** [comment] 2016-06-01 15:58
Hi guys!
The issues is reaper again. 

```
compile "com.braintreepayments.api:braintree:2.3.1"
compile "com.braintreepayments.api:drop-in:2.3.1"
```

```
Caused by java.lang.NullPointerException
com.braintreepayments.api.AddPaymentMethodViewController.initViews (AddPaymentMethodViewController.java:75)
com.braintreepayments.api.AddPaymentMethodViewController.<init> (AddPaymentMethodViewController.java:54)
com.braintreepayments.api.BraintreePaymentActivity.initAddPaymentMethodView (BraintreePaymentActivity.java:280)
com.braintreepayments.api.BraintreePaymentActivity.showAddPaymentMethodView (BraintreePaymentActivity.java:271)
com.braintreepayments.api.BraintreePaymentActivity.onCreate (BraintreePaymentActivity.java:118)
```

steps:
- open app (it can be demo)
- open Drop-In
- minimize the app
- kill app process
- re-lunch the app

**Comment by sdcoffey** [comment] 2016-06-01 23:56
Thanks @Duoblood,

The steps to repro are super helpful. Is there a specific device that this is happening on?

**Comment by Duoblood** [comment] 2016-06-02 20:40
@sdcoffey 

- Google Nexus 5 - Android 6.0.1; 
- Sony XPERIA Z5 - Android 5.1.1; 
- Lenovo A328 – Android 4.4.2; 
- HTC One M7 – Android 4.4.2

**Comment by sdcoffey** [comment] 2016-06-06 18:37
@Duoblood 

Can you confirm those repro steps? We are not able to reproduce this issue on any device.

**Comment by Duoblood** [comment] 2016-06-06 20:47
@sdcoffey 

I recorded a [movie](https://drive.google.com/file/d/0B5nm2EQH_AayYzJjUkpnOUowbVU/view?usp=sharing)  (skipped downloading)

**Comment by sdcoffey** [comment] 2016-06-06 21:42
@Duoblood 

Thanks for taking the time to record a video! It looks like you're stopping the process via ADB, and then re-opening the app. Is this the only way you're able to reproduce the crash? I would argue that such an action is well outside the bounds of what a user would actually encounter.

**Comment by Duoblood** [comment] 2016-06-07 16:56
@sdcoffey 

The first time it happened without using ADB (same steps).
I thought that Android kills activity which are running in the background when there is a need for memory. So I only emulated this situation, and caught it.

**Comment by sdcoffey** [comment] 2016-06-07 19:33
Ah, ok, thanks for the clarification. Our team member @quinnjn was able to replicate it by enabling these options in dev tools:
```
- Background process limit: No background processes
- Don’t keep activities
```

Thanks again for working with us on this, I'll keep you posted as we put a fix in.

**Closed** 2016-06-16 18:21 UTC
