### ISSUE TITLE
Drop in UI

### ISSUE THREAD

**Issue by jin9393** [braintree/braintree_android#132] opened 2016-12-05 08:34 UTC
I used async to fetch token from my server and at the end of the async i call the dropin function and nothing happen after that. However, when i hard coded the token into a string and place it into the dropin function the ui appear. Any way to solve this?

**Comment by lkorth** [comment] 2016-12-05 14:47
Duplicate of braintree/braintree-android-drop-in#7

**Closed by lkorth** 2016-12-05 14:47 UTC
